const AuditorWidgets = [
  {
    tab: 'es',
    title: 'Inherent Financial Risk',
    size: 'third',
    row: 1,
    column: 1,
    dataKey: 'inherent',
    widgetTemplate: 'top-three-category-with-pie-chart',
    link: '/reports/inherent-risk',
    isTimeBased: false,
  },
  {
    tab: 'es',
    title: 'Residual Financial Risk',
    size: 'third',
    row: 1,
    column: 1,
    dataKey: 'residual',
    link: '/reports/residual-risk',
    widgetTemplate: 'top-three-category-with-pie-chart',
    isTimeBased: false,
  },
  {
    tab: 'es',
    title: 'Loss Probability',
    size: 'third',
    row: 1,
    column: 1,
    dataKey: 'percent',
    link: '/reports/loss-probability',
    widgetTemplate: 'top-three-category-with-pie-chart',
    isTimeBased: false,
    valueType: 'percent',
  },
  {
    tab: 'es',
    title: 'Company Risk Profile',
    size: 'full',
    row: 2,
    column: 1,
    dataKey: 'residual-mitigated',
    widgetTemplate: 'horizontal-bar',
    isTimeBased: false,
  },
  {
    tab: 'es',
    title: 'Customer Business and Reputation Impact',
    size: 'full',
    row: 3,
    column: 1,
    dataKey: 'stock-market-metrics',
    widgetTemplate: 'business-impact',
    isTimeBased: false,
    valueType: 'percent',
  },
  {
    tab: 'es',
    title: 'Company Risk Trend',
    size: 'full',
    row: 4,
    column: 1,
    dataKey: 'inherent-residual-percent',
    widgetTemplate: 'vertical-bar',
    isTimeBased: false,
  },
  {
    tab: 'es',
    title: 'Overall Control Maturity',
    size: 'full',
    row: 5,
    column: 1,
    dataKey: 'control-metrics',
    widgetTemplate: 'just-header-horizontal',
    isTimeBased: false,
  },
  {
    tab: 'es',
    title: 'Peer Comparison',
    size: 'full',
    row: 6,
    column: 1,
    dataKey: 'residual-comparsion',
    widgetTemplate: 'header-with-line',
    isTimeBased: false,
  },
  {
    tab: 'po',
    title: 'Total Cyber Spend',
    size: 'full',
    row: 1,
    column: 1,
    dataKey: 'spending',
    widgetTemplate: 'just-header-horizontal',
    isTimeBased: false,
  },
  {
    tab: 'po',
    title: 'Cyber Spend',
    size: 'full',
    row: 2,
    column: 1,
    dataKey: 'spending',
    widgetTemplate: 'calculated-industry-average',
    isTimeBased: false,
  },
  {
    tab: 'po',
    title: 'Cyber Spend Investments',
    size: 'full',
    row: 3,
    column: 1,
    dataKey: 'spending',
    widgetTemplate: 'cyber-spend-investments',
    isTimeBased: false,
  },
  {
    tab: 'po',
    title: 'Mitigation Opportunities',
    size: 'full',
    row: 4,
    column: 1,
    dataKey: 'recommendations',
    widgetTemplate: 'mitigation-opportunities',
    isTimeBased: false,
  },
  {
    tab: 'po',
    title: 'Threat Exposure',
    size: 'full',
    row: 5,
    column: 1,
    dataKey: 'threats',
    widgetTemplate: 'threats-exposure',
    isTimeBased: false,
  },
  /*{
    tab: 'po',
    title: 'Critical Vulnerabilities',
    size: 'full',
    row: 6,
    column: 1,
    dataKey: 'vulnerabilities',
    widgetTemplate: 'critical-vulnerabilities',
    isTimeBased: false,
  },*/
  {
    tab: 'cs',
    title: 'Nist Compliance',
    size: 'full',
    row: 1,
    column: 1,
    dataKey: 'compliance-standards',
    widgetTemplate: 'nist-recs',
    link: '/reports/nist-csf',
    isTimeBased: false,
  },
  {
    tab: 'cs',
    title: 'ISO 270001 Compliance',
    size: 'full',
    row: 3,
    column: 1,
    dataKey: 'compliance-standards',
    widgetTemplate: 'iso-recs',
    link: '/reports/iso-270001',
    isTimeBased: false,
  },
  {
    tab: 'cs',
    title: 'CIS Critical Security Controls Version 8 Compliance',
    size: 'full',
    row: 4,
    column: 1,
    dataKey: 'compliance-standards',
    widgetTemplate: 'cis-recs',
    link: '/reports/cis',
    isTimeBased: false,
  },
  {
    tab: 'cs',
    title: 'CIS Critical Security Controls Version 8 Compliance',
    size: 'full',
    row: 2,
    column: 1,
    dataKey: 'compliance-standards',
    widgetTemplate: 'cis-recs',
    link: '/reports/cis',
    isTimeBased: false,
  },
  {
    tab: 'ht',
    title: 'Cyber Program Maturity',
    size: 'full',
    row: 1,
    column: 1,
    dataKey: 'historic-cyber-program-maturity',
    widgetTemplate: 'cyber-program-maturity',
    isTimeBased: false,
  },
  {
    tab: 'ht',
    title: 'Cyber Program Spend',
    size: 'full',
    row: 2,
    column: 1,
    dataKey: 'historic-spending',
    widgetTemplate: 'cyber-program-spend',
    isTimeBased: false,
  },
  {
    tab: 'ht',
    title: 'Cyber Program Risk Exposure',
    size: 'full',
    row: 3,
    column: 1,
    dataKey: 'historic-inherent',
    widgetTemplate: 'cyber-program-risk-exposure',
    isTimeBased: false,
  },
  {
    tab: 'ht',
    title: 'Compliance Coverage',
    size: 'full',
    row: 4,
    column: 1,
    dataKey: 'historic-nist-nys',
    widgetTemplate: 'compliance-coverage',
    isTimeBased: false,
  },
  {
    tab: 'ht',
    title: 'Threat Exposure',
    size: 'full',
    row: 5,
    column: 1,
    dataKey: 'historic-threat',
    widgetTemplate: 'threat-exposure',
    isTimeBased: false,
  },
]

export default AuditorWidgets
