const BoardWidgets = [
  {
    tab: 'es',
    title: 'Residual Financial Risk',
    size: 'full',
    row: 1,
    column: 1,
    dataKey: 'residual',
    link: '/reports/residual-risk',
    widgetTemplate: 'top-three-category-with-pie-chart',
    isTimeBased: false,
  },
  {
    tab: 'es',
    title: 'Customer Business and Reputation Impact',
    size: 'full',
    row: 3,
    column: 1,
    dataKey: 'stock-market-metrics',
    widgetTemplate: 'business-impact',
    isTimeBased: false,
    valueType: 'percent',
  },
  {
    tab: 'es',
    title: 'Stock Impact',
    size: 'full',
    row: 2,
    column: 2,
    isTimeBased: false,
    dataKey: 'stock-market-metrics',
    widgetTemplate: 'stock-impact',
  },
  {
    tab: 'es',
    title: 'Company Risk Trend',
    size: 'full',
    row: 3,
    column: 1,
    dataKey: 'inherent-residual-percent',
    widgetTemplate: 'vertical-bar',
    isTimeBased: false,
  },
  {
    tab: 'es',
    title: 'Overall Control Maturity',
    size: 'full',
    row: 4,
    column: 1,
    dataKey: 'control-metrics',
    widgetTemplate: 'just-header-horizontal',
    isTimeBased: false,
  },
  {
    tab: 'es',
    title: 'Peer Comparison',
    size: 'full',
    row: 5,
    column: 1,
    dataKey: 'residual-comparsion',
    widgetTemplate: 'header-with-line',
    isTimeBased: false,
  },
  /*{
    tab: 'po',
    title: 'Critical Vulnerabilities',
    size: 'full',
    row: 1,
    column: 1,
    dataKey: 'vulnerabilities',
    widgetTemplate: 'critical-vulnerabilities',
    isTimeBased: false,
  },*/
  {
    tab: 'cs',
    title: 'NIST Compliance',
    size: 'full',
    row: 1,
    column: 1,
    dataKey: 'compliance-standards',
    widgetTemplate: 'nist-recs',
    link: '/reports/nist-csf',
    isTimeBased: false,
  },
  {
    tab: 'cs',
    title: 'NY DFS Compliance ',
    size: 'full',
    row: 2,
    column: 1,
    dataKey: 'compliance-standards',
    widgetTemplate: 'nys-recs',
    link: '/reports/nys-dfs',
    isTimeBased: false,
  },
  {
    tab: 'cs',
    title: 'ISO 270001 Compliance',
    size: 'full',
    row: 3,
    column: 1,
    dataKey: 'compliance-standards',
    widgetTemplate: 'iso-recs',
    link: '/reports/iso-270001',
    isTimeBased: false,
  },
  {
    tab: 'cs',
    title: 'CIS Critical Security Controls Version 8 Compliance',
    size: 'full',
    row: 4,
    column: 1,
    dataKey: 'compliance-standards',
    widgetTemplate: 'cis-recs',
    link: '/reports/cis',
    isTimeBased: false,
  },
  {
    tab: 'ht',
    title: 'Cyber Program Risk Exposure',
    size: 'full',
    row: 1,
    column: 1,
    dataKey: 'historic-inherent',
    widgetTemplate: 'cyber-program-risk-exposure',
    isTimeBased: false,
  },
  {
    tab: 'ht',
    title: 'Threat Exposure',
    size: 'full',
    row: 2,
    column: 1,
    dataKey: 'historic-threat',
    widgetTemplate: 'threat-exposure',
    isTimeBased: false,
  },
]
export default BoardWidgets
