const CisoWidgets = [
  {
    tab: 'es',
    title: 'Inherent Financial Risk',
    tooltip:
      'Inherent risk is the risk posed by an error or omission in a financial statement due to a factor other than a failure of internal control.',
    size: 'third',
    row: 1,
    column: 1,
    dataKey: 'inherent',
    widgetTemplate: 'top-three-category-with-pie-chart',
    link: '/reports/inherent-risk',
    isTimeBased: false,
  },
  {
    tab: 'es',
    title: 'Residual Financial Risk',
    tooltip:
      'The residual risk is the amount of risk or danger associated with an action or event remaining after natural or inherent risks have been reduced by risk controls.',
    size: 'third',
    row: 1,
    column: 1,
    dataKey: 'residual',
    link: '/reports/residual-risk',
    widgetTemplate: 'top-three-category-with-pie-chart',
    isTimeBased: false,
  },
  {
    tab: 'es',
    title: 'Loss Probability',
    tooltip:
      'Loss Proability is defined as the probability that a lossing event will occur. Like risk, probability has both objective and subjective aspects.',
    size: 'third',
    row: 1,
    column: 1,
    dataKey: 'percent',
    widgetTemplate: 'top-three-category-with-pie-chart',
    link: '/reports/loss-probability',
    isTimeBased: false,
    valueType: 'percent',
  },
  {
    tab: 'es',
    title: 'Company Risk Profile',
    tooltip:
      'The residual risk is the amount of risk or danger associated with an action or event remaining after natural or inherent risks have been reduced by risk controls.',
    size: 'full',
    row: 2,
    column: 1,
    dataKey: 'residual-mitigated',
    widgetTemplate: 'horizontal-bar',
    isTimeBased: false,
  },
  {
    tab: 'es',
    title: 'Customer Business and Reputation Impact',
    tooltip: `A business's reputation is how the public, including customers, perceive the company and its operations. It can be positive or negative and can change over time. A good reputation can build trust, credibility, and loyalty among customers, while a negative reputation can damage a company's image and lead to loss of sales.`,
    size: 'full',
    row: 3,
    column: 1,
    dataKey: 'stock-market-metrics',
    widgetTemplate: 'business-impact',
    isTimeBased: false,
    valueType: 'percent',
  },
  {
    tab: 'es',
    title: 'Stock Impact',
    tooltip: `This measures the impact to stock price based on the risk factors associated with the current control set.`,
    size: 'full',
    row: 3,
    column: 2,
    isTimeBased: false,
    dataKey: 'stock-market-metrics-impact',
    widgetTemplate: 'stock-impact',
  },
  {
    tab: 'es',
    title: 'Company Risk Trend',
    size: 'full',
    row: 4,
    column: 1,
    dataKey: 'inherent-residual-percent',
    widgetTemplate: 'vertical-bar',
    isTimeBased: false,
  },
  {
    tab: 'es',
    title: 'Overall Control Maturity',
    size: 'full',
    row: 5,
    column: 1,
    dataKey: 'control-metrics',
    widgetTemplate: 'just-header-horizontal',
    isTimeBased: false,
  },
  {
    tab: 'es',
    title: 'Peer Comparison',
    size: 'full',
    row: 6,
    column: 1,
    dataKey: 'residual-comparsion',
    widgetTemplate: 'header-with-line',
    isTimeBased: false,
  },
  {
    tab: 'po',
    title: 'Total Cyber Spend',
    size: 'full',
    row: 1,
    column: 1,
    dataKey: 'spending',
    widgetTemplate: 'just-header-horizontal',
    isTimeBased: false,
  },
  {
    tab: 'po',
    title: 'Cyber Spend',
    size: 'full',
    row: 2,
    column: 1,
    dataKey: 'spending',
    widgetTemplate: 'calculated-industry-average',
    isTimeBased: false,
  },
  {
    tab: 'po',
    title: 'Cyber Spend Investments',
    size: 'full',
    row: 3,
    column: 1,
    dataKey: 'spending',
    widgetTemplate: 'cyber-spend-investments',
    isTimeBased: false,
  },
  {
    tab: 'po',
    title: 'Mitigation Opportunities',
    size: 'full',
    row: 4,
    column: 1,
    dataKey: 'recommendations',
    widgetTemplate: 'mitigation-opportunities',
    isTimeBased: false,
  },
  {
    tab: 'po',
    title: 'Threat Exposure',
    size: 'full',
    row: 5,
    column: 1,
    dataKey: 'threats',
    widgetTemplate: 'threats-exposure',
    isTimeBased: false,
  },
  /*{
    tab: 'po',
    title: 'Critical Vulnerabilities',
    size: 'full',
    row: 6,
    column: 1,
    dataKey: 'vulnerabilities',
    widgetTemplate: 'critical-vulnerabilities',
    isTimeBased: false,
  },*/
  {
    tab: 'cs',
    title: 'NIST Compliance',
    size: 'full',
    row: 1,
    column: 1,
    dataKey: 'compliance-standards',
    widgetTemplate: 'nist-recs',
    link: '/reports/nist-csf',
    isTimeBased: false,
  },
  {
    tab: 'cs',
    title: 'NY DFS Compliance',
    size: 'full',
    row: 2,
    column: 1,
    dataKey: 'compliance-standards',
    widgetTemplate: 'nys-recs',
    link: '/reports/ny-dfs',
    isTimeBased: false,
  },
  {
    tab: 'cs',
    title: 'ISO 270001 Compliance',
    size: 'full',
    row: 3,
    column: 1,
    dataKey: 'compliance-standards',
    widgetTemplate: 'iso-recs',
    link: '/reports/iso-270001',
    isTimeBased: false,
  },
  {
    tab: 'cs',
    title: 'CIS Critical Security Controls Version 8 Compliance',
    size: 'full',
    row: 4,
    column: 1,
    dataKey: 'compliance-standards',
    widgetTemplate: 'cis-recs',
    link: '/reports/cis',
    isTimeBased: false,
  },
  {
    tab: 'ht',
    title: 'Cyber Program Maturity',
    size: 'full',
    row: 1,
    column: 1,
    dataKey: 'historic-cyber-program-maturity',
    widgetTemplate: 'cyber-program-maturity',
    isTimeBased: false,
  },
  {
    tab: 'ht',
    title: 'Cyber Program Spend',
    size: 'full',
    row: 2,
    column: 1,
    dataKey: 'historic-spending',
    widgetTemplate: 'cyber-program-spend',
    isTimeBased: false,
  },
  {
    tab: 'ht',
    title: 'Cyber Program Risk Exposure',
    size: 'full',
    row: 3,
    column: 1,
    dataKey: 'historic-inherent',
    widgetTemplate: 'cyber-program-risk-exposure',
    isTimeBased: false,
  },
  {
    tab: 'ht',
    title: 'Compliance Coverage',
    size: 'full',
    row: 4,
    column: 1,
    dataKey: 'historic-nist-nys',
    widgetTemplate: 'compliance-coverage',
    isTimeBased: false,
  },
  {
    tab: 'ht',
    title: 'Threat Exposure',
    size: 'full',
    row: 5,
    column: 1,
    dataKey: 'historic-threat',
    widgetTemplate: 'threat-exposure',
    isTimeBased: false,
  },
]

export default CisoWidgets
