import {
  Activity,
  ActivityHeart,
  Airplay,
  Airpods,
  AlarmClock,
  AlarmClockCheck,
  AlarmClockMinus,
  AlarmClockOff,
  AlarmClockPlus,
  AlertCircle,
  AlertHexagon,
  AlertOctagon,
  AlertSquare,
  AlertTriangle,
  AlignBottom01,
  AlignBottom02,
  AlignCenter,
  AlignHorizontalCentre01,
  AlignHorizontalCentre02,
  AlignJustify,
  AlignLeft,
  AlignLeft01,
  AlignLeft02,
  AlignRight,
  AlignRight01,
  AlignRight02,
  AlignTop01,
  AlignTop02,
  AlignVerticalCenter01,
  AlignVerticalCenter02,
  Anchor,
  Annotation,
  AnnotationAlert,
  AnnotationCheck,
  AnnotationDots,
  AnnotationHeart,
  AnnotationInfo,
  AnnotationPlus,
  AnnotationQuestion,
  AnnotationX,
  Announcement01,
  Announcement02,
  Announcement03,
  Archive,
  ArrowBlockDown,
  ArrowBlockLeft,
  ArrowBlockRight,
  ArrowBlockUp,
  ArrowCircleBrokenDown,
  ArrowCircleBrokenDownLeft,
  ArrowCircleBrokenDownRight,
  ArrowCircleBrokenLeft,
  ArrowCircleBrokenRight,
  ArrowCircleBrokenUp,
  ArrowCircleBrokenUpLeft,
  ArrowCircleBrokenUpRight,
  ArrowCircleDown,
  ArrowCircleDownLeft,
  ArrowCircleDownRight,
  ArrowCircleLeft,
  ArrowCircleRight,
  ArrowCircleUp,
  ArrowCircleUpLeft,
  ArrowCircleUpRight,
  ArrowDown,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowLeft,
  ArrowNarrowDown,
  ArrowNarrowDownLeft,
  ArrowNarrowDownRight,
  ArrowNarrowLeft,
  ArrowNarrowRight,
  ArrowNarrowUp,
  ArrowNarrowUpLeft,
  ArrowNarrowUpRight,
  ArrowRight,
  ArrowsDown,
  ArrowsLeft,
  ArrowSquareDown,
  ArrowSquareDownLeft,
  ArrowSquareDownRight,
  ArrowSquareLeft,
  ArrowSquareRight,
  ArrowSquareUp,
  ArrowSquareUpLeft,
  ArrowSquareUpRight,
  ArrowsRight,
  ArrowsTriangle,
  ArrowsUp,
  ArrowUp,
  ArrowUpLeft,
  ArrowUpRight,
  Asterisk01,
  Asterisk02,
  Atom01,
  Atom02,
  AtSign,
  Attachment01,
  Attachment02,
  Award01,
  Award02,
  Award03,
  Award04,
  Award05,
  Backpack,
  Bank,
  BankNote01,
  BankNote02,
  BankNote03,
  BarChart01,
  BarChart02,
  BarChart03,
  BarChart04,
  BarChart05,
  BarChart06,
  BarChart07,
  BarChart08,
  BarChart09,
  BarChart10,
  BarChart11,
  BarChart12,
  BarChartCircle01,
  BarChartCircle02,
  BarChartCircle03,
  BarChartSquare01,
  BarChartSquare02,
  BarChartSquare03,
  BarChartSquareDown,
  BarChartSquareMinus,
  BarChartSquarePlus,
  BarChartSquareUp,
  BarLineChart,
  BatteryCharging01,
  BatteryCharging02,
  BatteryEmpty,
  BatteryFull,
  BatteryLow,
  BatteryMid,
  Beaker01,
  Beaker02,
  Bell01,
  Bell02,
  Bell03,
  Bell04,
  BellMinus,
  BellOff01,
  BellOff02,
  BellOff03,
  BellPlus,
  BellRinging01,
  BellRinging02,
  BellRinging03,
  BellRinging04,
  BezierCurve01,
  BezierCurve02,
  BezierCurve03,
  BluetoothConnect,
  BluetoothOff,
  BluetoothOn,
  BluetoothSignal,
  Bold01,
  Bold02,
  BoldSquare,
  BookClosed,
  Bookmark,
  BookmarkAdd,
  BookmarkCheck,
  BookmarkMinus,
  BookmarkX,
  BookOpen01,
  BookOpen02,
  Box,
  Brackets,
  BracketsCheck,
  BracketsEllipses,
  BracketsMinus,
  BracketsPlus,
  BracketsSlash,
  BracketsX,
  Briefcase01,
  Briefcase02,
  Browser,
  Brush01,
  Brush02,
  Brush03,
  Building01,
  Building02,
  Building03,
  Building04,
  Building05,
  Building06,
  Building07,
  Building08,
  Bus,
  Calculator,
  Calendar,
  CalendarCheck01,
  CalendarCheck02,
  CalendarDate,
  CalendarHeart01,
  CalendarHeart02,
  CalendarMinus01,
  CalendarMinus02,
  CalendarPlus01,
  CalendarPlus02,
  Camera01,
  Camera02,
  Camera03,
  CameraLens,
  CameraOff,
  CameraPlus,
  Certificate01,
  Certificate02,
  ChartBreakoutCircle,
  ChartBreakoutSquare,
  Check,
  CheckCircle,
  CheckCircleBroken,
  CheckDone01,
  CheckDone02,
  CheckHeart,
  CheckSquare,
  CheckSquareBroken,
  CheckVerified01,
  CheckVerified02,
  CheckVerified03,
  ChevronDown,
  ChevronDownDouble,
  ChevronLeft,
  ChevronLeftDouble,
  ChevronRight,
  ChevronRightDouble,
  ChevronSelectorHorizontal,
  ChevronSelectorVertical,
  ChevronUp,
  ChevronUpDouble,
  ChromeCast,
  Circle,
  CircleCut,
  Clapperboard,
  Clipboard,
  ClipboardAttachment,
  ClipboardCheck,
  ClipboardDownload,
  ClipboardMinus,
  ClipboardPlus,
  ClipboardX,
  Clock,
  ClockCheck,
  ClockFastForward,
  ClockPlus,
  ClockRefresh,
  ClockRewind,
  ClockSnooze,
  ClockStopwatch,
  Cloud01,
  Cloud02,
  Cloud03,
  CloudBlank01,
  CloudBlank02,
  CloudLightning,
  CloudMoon,
  CloudOff,
  CloudRaining01,
  CloudRaining02,
  CloudRaining03,
  CloudRaining04,
  CloudRaining05,
  CloudRaining06,
  CloudSnowing01,
  CloudSnowing02,
  CloudSun01,
  CloudSun02,
  CloudSun03,
  Code01,
  Code02,
  CodeBrowser,
  CodeCircle01,
  CodeCircle02,
  CodeCircle03,
  Codepen,
  CodeSnippet01,
  CodeSnippet02,
  CodeSquare01,
  CodeSquare02,
  Coins01,
  Coins02,
  Coins03,
  Coins04,
  CoinsHand,
  CoinsStacked01,
  CoinsStacked02,
  CoinsStacked03,
  CoinsStacked04,
  CoinsSwap01,
  CoinsSwap02,
  Colors,
  Columns01,
  Columns02,
  Columns03,
  Command,
  Compass,
  Compass01,
  Compass02,
  Compass03,
  Container,
  Contrast01,
  Contrast02,
  Contrast03,
  Copy01,
  Copy02,
  Copy03,
  Copy04,
  Copy05,
  Copy06,
  Copy07,
  CornerDownLeft,
  CornerDownRight,
  CornerLeftDown,
  CornerLeftUp,
  CornerRightDown,
  CornerRightUp,
  CornerUpLeft,
  CornerUpRight,
  CpuChip01,
  CpuChip02,
  CreditCard01,
  CreditCard02,
  CreditCardCheck,
  CreditCardDown,
  CreditCardDownload,
  CreditCardEdit,
  CreditCardLock,
  CreditCardMinus,
  CreditCardPlus,
  CreditCardRefresh,
  CreditCardSearch,
  CreditCardShield,
  CreditCardUp,
  CreditCardUpload,
  CreditCardX,
  Crop01,
  Crop02,
  Cryptocurrency01,
  Cryptocurrency02,
  Cryptocurrency03,
  Cryptocurrency04,
  Cube01,
  Cube02,
  Cube03,
  Cube04,
  CubeOutline,
  CurrencyBitcoin,
  CurrencyBitcoinCircle,
  CurrencyDollar,
  CurrencyDollarCircle,
  CurrencyEthereum,
  CurrencyEthereumCircle,
  CurrencyEuro,
  CurrencyEuroCircle,
  CurrencyPound,
  CurrencyPoundCircle,
  CurrencyRuble,
  CurrencyRubleCircle,
  CurrencyRupee,
  CurrencyRupeeCircle,
  CurrencyYen,
  CurrencyYenCircle,
  Cursor01,
  Cursor02,
  Cursor03,
  Cursor04,
  CursorBox,
  CursorClick01,
  CursorClick02,
  Data,
  Database01,
  Database02,
  Database03,
  Dataflow01,
  Dataflow02,
  Dataflow03,
  Dataflow04,
  Delete,
  Diamond01,
  Diamond02,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Disc01,
  Disc02,
  DistributeSpacingHorizontal,
  DistributeSpacingVertical,
  Divide01,
  Divide02,
  Divide03,
  Divider,
  Dotpoints01,
  Dotpoints02,
  DotsGrid,
  DotsHorizontal,
  DotsVertical,
  Download01,
  Download02,
  Download03,
  Download04,
  DownloadCloud01,
  DownloadCloud02,
  Drop,
  Droplets01,
  Droplets02,
  Droplets03,
  Dropper,
  Edit01,
  Edit02,
  Edit03,
  Edit04,
  Edit05,
  Equal,
  EqualNot,
  Eraser,
  Expand01,
  Expand02,
  Expand03,
  Expand04,
  Expand05,
  Expand06,
  Eye,
  EyeOff,
  FaceContent,
  FaceFrown,
  FaceHappy,
  FaceId,
  FaceIdSquare,
  FaceNeutral,
  FaceSad,
  FaceSmile,
  FaceWink,
  FastBackward,
  FastForward,
  Feather,
  Figma,
  File01,
  File02,
  File03,
  File04,
  File05,
  File06,
  File07,
  FileAttachment01,
  FileAttachment02,
  FileAttachment03,
  FileAttachment04,
  FileAttachment05,
  FileCheck01,
  FileCheck02,
  FileCheck03,
  FileCode01,
  FileCode02,
  FileDownload01,
  FileDownload02,
  FileDownload03,
  FileHeart01,
  FileHeart02,
  FileHeart03,
  FileLock01,
  FileLock02,
  FileLock03,
  FileMinus01,
  FileMinus02,
  FileMinus03,
  FilePlus01,
  FilePlus02,
  FilePlus03,
  FileQuestion01,
  FileQuestion02,
  FileQuestion03,
  FileSearch01,
  FileSearch02,
  FileSearch03,
  FileShield01,
  FileShield02,
  FileShield03,
  FileX01,
  FileX02,
  FileX03,
  Film01,
  Film02,
  Film03,
  FilterFunnel01,
  FilterFunnel02,
  FilterLines,
  Fingerprint01,
  Fingerprint02,
  Fingerprint03,
  Fingerprint04,
  Flag01,
  Flag02,
  Flag03,
  Flag04,
  Flag05,
  Flag06,
  Flash,
  FlashOff,
  FlexAlignBottom,
  FlexAlignLeft,
  FlexAlignRight,
  FlexAlignTop,
  FlipBackward,
  FlipForward,
  Folder,
  FolderCheck,
  FolderClosed,
  FolderCode,
  FolderDownload,
  FolderLock,
  FolderMinus,
  FolderPlus,
  FolderQuestion,
  FolderSearch,
  FolderShield,
  FolderX,
  Framer,
  GamingPad01,
  GamingPad02,
  Gift01,
  Gift02,
  GitBranch01,
  GitBranch02,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Glasses01,
  Glasses02,
  Globe01,
  Globe02,
  Globe03,
  Globe04,
  Globe05,
  Globe06,
  GoogleChrome,
  GraduationHat01,
  GraduationHat02,
  Grid01,
  Grid02,
  Grid03,
  GridDotsBlank,
  GridDotsBottom,
  GridDotsHorizontalCenter,
  GridDotsLeft,
  GridDotsOuter,
  GridDotsRight,
  GridDotsTop,
  GridDotsVerticalCenter,
  Hand,
  HardDrive,
  Hash01,
  Hash02,
  Heading01,
  Heading02,
  HeadingSquare,
  Headphones01,
  Headphones02,
  Heart,
  HeartCircle,
  HeartHand,
  HeartHexagon,
  HeartOctagon,
  HeartRounded,
  Hearts,
  HeartSquare,
  HelpCircle,
  HelpOctagon,
  HelpSquare,
  Hexagon01,
  Hexagon02,
  Home01,
  Home02,
  Home03,
  Home04,
  Home05,
  HomeLine,
  HomeSmile,
  HorizontalBarChart01,
  HorizontalBarChart02,
  HorizontalBarChart03,
  Hourglass01,
  Hourglass02,
  Hourglass03,
  Hurricane01,
  Hurricane02,
  Hurricane03,
  Image01,
  Image02,
  Image03,
  Image04,
  Image05,
  ImageCheck,
  ImageDown,
  ImageIndentLeft,
  ImageIndentRight,
  ImageLeft,
  ImagePlus,
  ImageRight,
  ImageUp,
  ImageUser,
  ImageUserCheck,
  ImageUserDown,
  ImageUserLeft,
  ImageUserPlus,
  ImageUserRight,
  ImageUserUp,
  ImageUserX,
  ImageX,
  Inbox01,
  Inbox02,
  InfoCircle,
  InfoHexagon,
  InfoOctagon,
  InfoSquare,
  IntersectCircle,
  IntersectSquare,
  Infinity,
  Italic01,
  Italic02,
  ItalicSquare,
  Key01,
  Key02,
  Keyboard01,
  Keyboard02,
  Laptop01,
  Laptop02,
  LayerSingle,
  LayersThree01,
  LayersThree02,
  LayersTwo01,
  LayersTwo02,
  LayoutAlt01,
  LayoutAlt02,
  LayoutAlt03,
  LayoutAlt04,
  LayoutBottom,
  LayoutGrid01,
  LayoutGrid02,
  LayoutLeft,
  LayoutRight,
  LayoutTop,
  LeftIndent01,
  LeftIndent02,
  LetterSpacing01,
  LetterSpacing02,
  LifeBuoy01,
  LifeBuoy02,
  Lightbulb01,
  Lightbulb02,
  Lightbulb03,
  Lightbulb04,
  Lightbulb05,
  Lightning01,
  Lightning02,
  LineChartDown01,
  LineChartDown02,
  LineChartDown03,
  LineChartDown04,
  LineChartDown05,
  LineChartUp01,
  LineChartUp02,
  LineChartUp03,
  LineChartUp04,
  LineChartUp05,
  LineHeight,
  Link01,
  Link02,
  Link03,
  Link04,
  Link05,
  LinkBroken01,
  LinkBroken02,
  LinkExternal01,
  LinkExternal02,
  List,
  Loading01,
  Loading02,
  Loading03,
  Lock01,
  Lock02,
  Lock03,
  Lock04,
  LockKeyholeCircle,
  LockKeyholeSquare,
  LockUnlocked01,
  LockUnlocked02,
  LockUnlocked03,
  LockUnlocked04,
  LogIn01,
  LogIn02,
  LogIn03,
  LogIn04,
  LogOut01,
  LogOut02,
  LogOut03,
  LogOut04,
  Luggage01,
  Luggage02,
  Luggage03,
  MagicWand01,
  MagicWand02,
  Mail01,
  Mail02,
  Mail03,
  Mail04,
  Mail05,
  Map01,
  Map02,
  Mark,
  MarkerPin01,
  MarkerPin02,
  MarkerPin03,
  MarkerPin04,
  MarkerPin05,
  MarkerPin06,
  Maximize01,
  Maximize02,
  MedicalCircle,
  MedicalCross,
  MedicalSquare,
  Menu01,
  Menu02,
  Menu03,
  Menu04,
  Menu05,
  MessageAlertCircle,
  MessageAlertSquare,
  MessageChatCircle,
  MessageChatSquare,
  MessageCheckCircle,
  MessageCheckSquare,
  MessageCircle01,
  MessageCircle02,
  MessageDotsCircle,
  MessageDotsSquare,
  MessageHeartCircle,
  MessageHeartSquare,
  MessageNotificationCircle,
  MessageNotificationSquare,
  MessagePlusCircle,
  MessagePlusSquare,
  MessageQuestionCircle,
  MessageQuestionSquare,
  MessageSmileCircle,
  MessageSmileSquare,
  MessageSquare01,
  MessageSquare02,
  MessageTextCircle01,
  MessageTextCircle02,
  MessageTextSquare01,
  MessageTextSquare02,
  MessageXCircle,
  MessageXSquare,
  Microphone01,
  Microphone02,
  MicrophoneOff01,
  MicrophoneOff02,
  Microscope,
  Minimize01,
  Minimize02,
  Minus,
  MinusCircle,
  MinusSquare,
  Modem01,
  Modem02,
  Monitor01,
  Monitor02,
  Monitor03,
  Monitor04,
  Monitor05,
  Moon01,
  Moon02,
  MoonEclipse,
  MoonStar,
  Mouse,
  Move,
  MusicNote01,
  MusicNote02,
  MusicNotePlus,
  NavigationPointer01,
  NavigationPointer02,
  NavigationPointerOff01,
  NavigationPointerOff02,
  NotificationBox,
  NotificationMessage,
  NotificationText,
  Octagon,
  Package,
  PackageCheck,
  PackageMinus,
  PackagePlus,
  PackageSearch,
  PackageX,
  Paint,
  PaintPour,
  Palette,
  Paperclip,
  ParagraphSpacing,
  ParagraphWrap,
  Passcode,
  PasscodeLock,
  Passport,
  PauseCircle,
  PauseSquare,
  Pencil01,
  Pencil02,
  PencilLine,
  Pentagon,
  PenTool01,
  PenTool02,
  PenToolMinus,
  PenToolPlus,
  Percent01,
  Percent02,
  Percent03,
  Perspective01,
  Perspective02,
  Phone,
  Phone01,
  Phone02,
  PhoneCall01,
  PhoneCall02,
  PhoneHangUp,
  PhoneIncoming01,
  PhoneIncoming02,
  PhoneOutgoing01,
  PhoneOutgoing02,
  PhonePause,
  PhonePlus,
  PhoneX,
  PieChart01,
  PieChart02,
  PieChart03,
  PieChart04,
  PiggyBank01,
  PiggyBank02,
  Pilcrow01,
  Pilcrow02,
  PilcrowSquare,
  Pin01,
  Pin02,
  Placeholder,
  Plane,
  Play,
  PlayCircle,
  PlaySquare,
  Plus,
  PlusCircle,
  PlusSquare,
  Podcast,
  Power01,
  Power02,
  Power03,
  PresentationChart01,
  PresentationChart02,
  PresentationChart03,
  Printer,
  PuzzlePiece01,
  PuzzlePiece02,
  QrCode01,
  QrCode02,
  Receipt,
  ReceiptCheck,
  Recording01,
  Recording02,
  Recording03,
  Reflect01,
  Reflect02,
  RefreshCcw01,
  RefreshCcw02,
  RefreshCcw03,
  RefreshCcw04,
  RefreshCcw05,
  RefreshCw01,
  RefreshCw02,
  RefreshCw03,
  RefreshCw04,
  RefreshCw05,
  Repeat01,
  Repeat02,
  Repeat03,
  Repeat04,
  ReverseLeft,
  ReverseRight,
  RightIndent01,
  RightIndent02,
  Rocket01,
  Rocket02,
  RollerBrush,
  Route,
  Rows01,
  Rows02,
  Rows03,
  Rss01,
  Rss02,
  Ruler,
  Safe,
  Sale01,
  Sale02,
  Sale03,
  Sale04,
  Save01,
  Save02,
  Save03,
  Scale01,
  Scale02,
  Scale03,
  Scales01,
  Scales02,
  Scan,
  Scissors01,
  Scissors02,
  ScissorsCut01,
  ScissorsCut02,
  SearchLg,
  SearchMd,
  SearchRefraction,
  SearchSm,
  Send01,
  Send02,
  Send03,
  Server01,
  Server02,
  Server03,
  Server04,
  Server05,
  Server06,
  Settings01,
  Settings02,
  Settings03,
  Settings04,
  Share01,
  Share02,
  Share03,
  Share04,
  Share05,
  Share06,
  Share07,
  Shield01,
  Shield02,
  Shield03,
  ShieldDollar,
  ShieldOff,
  ShieldPlus,
  ShieldTick,
  ShieldZap,
  ShoppingBag01,
  ShoppingBag02,
  ShoppingBag03,
  ShoppingCart01,
  ShoppingCart02,
  ShoppingCart03,
  Shuffle01,
  Shuffle02,
  Signal01,
  Signal02,
  Signal03,
  Simcard,
  Skew,
  SkipBack,
  SkipForward,
  SlashCircle01,
  SlashCircle02,
  SlashDivider,
  SlashOctagon,
  Sliders01,
  Sliders02,
  Sliders03,
  Sliders04,
  Snowflake01,
  Snowflake02,
  SpacingHeight01,
  SpacingHeight02,
  SpacingWidth01,
  SpacingWidth02,
  Speaker01,
  Speaker02,
  Speaker03,
  Speedometer01,
  Speedometer02,
  Speedometer03,
  Speedometer04,
  Square,
  Stand,
  Star01,
  Star02,
  Star03,
  Star04,
  Star05,
  Star06,
  Star07,
  Stars01,
  Stars02,
  Stars03,
  StickerCircle,
  StickerSquare,
  Stop,
  StopCircle,
  StopSquare,
  Strikethrough01,
  Strikethrough02,
  StrikethroughSquare,
  Subscript,
  Sun,
  Sunrise,
  Sunset,
  SunSetting01,
  SunSetting02,
  SunSetting03,
  SwitchHorizontal01,
  SwitchHorizontal02,
  SwitchVertical01,
  SwitchVertical02,
  Table,
  Tablet01,
  Tablet02,
  Tag01,
  Tag02,
  Tag03,
  Target01,
  Target02,
  Target03,
  Target04,
  Target05,
  Telescope,
  Terminal,
  TerminalBrowser,
  TerminalCircle,
  TerminalSquare,
  TextInput,
  Thermometer01,
  Thermometer02,
  Thermometer03,
  ThermometerCold,
  ThermometerWarm,
  ThumbsDown,
  ThumbsUp,
  Ticket01,
  Ticket02,
  Toggle01Left,
  Toggle01Right,
  Toggle02Left,
  Toggle02Right,
  Toggle03Left,
  Toggle03Right,
  Tool01,
  Tool02,
  Train,
  Tram,
  Transform,
  Translate01,
  Translate02,
  Trash01,
  Trash02,
  Trash03,
  Trash04,
  TrendDown01,
  TrendDown02,
  TrendUp01,
  TrendUp02,
  Triangle,
  Trophy01,
  Trophy02,
  Truck01,
  Truck02,
  Tv01,
  Tv02,
  Tv03,
  Type01,
  Type02,
  TypeSquare,
  TypeStrikethrough01,
  TypeStrikethrough02,
  Umbrella01,
  Umbrella02,
  Umbrella03,
  Underline01,
  Underline02,
  UnderlineSquare,
  Upload01,
  Upload02,
  Upload03,
  Upload04,
  UploadCloud01,
  UploadCloud02,
  UsbFlashDrive,
  User01,
  User02,
  User03,
  UserCheck01,
  UserCheck02,
  UserCircle,
  UserDown01,
  UserDown02,
  UserEdit,
  UserLeft01,
  UserLeft02,
  UserMinus01,
  UserMinus02,
  UserPlus01,
  UserPlus02,
  UserRight01,
  UserRight02,
  Users01,
  Users02,
  Users03,
  UsersCheck,
  UsersDown,
  UsersEdit,
  UsersLeft,
  UsersMinus,
  UsersPlus,
  UserSquare,
  UsersRight,
  UsersUp,
  UsersX,
  UserUp01,
  UserUp02,
  UserX01,
  UserX02,
  Variable,
  VideoRecorder,
  VideoRecorderOff,
  Virus,
  Voicemail,
  VolumeMax,
  VolumeMin,
  VolumeMinus,
  VolumePlus,
  VolumeX,
  Wallet01,
  Wallet02,
  Wallet03,
  Wallet04,
  Wallet05,
  WatchCircle,
  WatchSquare,
  Waves,
  Webcam01,
  Webcam02,
  Wifi,
  WifiOff,
  Wind01,
  Wind02,
  Wind03,
  X,
  XCircle,
  XClose,
  XSquare,
  Youtube,
  Zap,
  ZapCircle,
  ZapFast,
  ZapOff,
  ZapSquare,
  ZoomIn,
  ZoomOut,
} from '@untitled-ui/icons-react'

const icons = [
  { label: 'Activity', icon: <Activity /> },
  { label: 'ActivityHeart', icon: <ActivityHeart /> },
  { label: 'Airplay', icon: <Airplay /> },
  { label: 'Airpods', icon: <Airpods /> },
  { label: 'AlarmClock', icon: <AlarmClock /> },
  { label: 'AlarmClockCheck', icon: <AlarmClockCheck /> },
  { label: 'AlarmClockMinus', icon: <AlarmClockMinus /> },
  { label: 'AlarmClockOff', icon: <AlarmClockOff /> },
  { label: 'AlarmClockPlus', icon: <AlarmClockPlus /> },
  { label: 'AlertCircle', icon: <AlertCircle /> },
  { label: 'AlertHexagon', icon: <AlertHexagon /> },
  { label: 'AlertOctagon', icon: <AlertOctagon /> },
  { label: 'AlertSquare', icon: <AlertSquare /> },
  { label: 'AlertTriangle', icon: <AlertTriangle /> },
  { label: 'AlignBottom01', icon: <AlignBottom01 /> },
  { label: 'AlignBottom02', icon: <AlignBottom02 /> },
  { label: 'AlignCenter', icon: <AlignCenter /> },
  { label: 'AlignHorizontalCentre01', icon: <AlignHorizontalCentre01 /> },
  { label: 'AlignHorizontalCentre02', icon: <AlignHorizontalCentre02 /> },
  { label: 'AlignJustify', icon: <AlignJustify /> },
  { label: 'AlignLeft', icon: <AlignLeft /> },
  { label: 'AlignLeft01', icon: <AlignLeft01 /> },
  { label: 'AlignLeft02', icon: <AlignLeft02 /> },
  { label: 'AlignRight', icon: <AlignRight /> },
  { label: 'AlignRight01', icon: <AlignRight01 /> },
  { label: 'AlignRight02', icon: <AlignRight02 /> },
  { label: 'AlignTop01', icon: <AlignTop01 /> },
  { label: 'AlignTop02', icon: <AlignTop02 /> },
  { label: 'AlignVerticalCenter01', icon: <AlignVerticalCenter01 /> },
  { label: 'AlignVerticalCenter02', icon: <AlignVerticalCenter02 /> },
  { label: 'Anchor', icon: <Anchor /> },
  { label: 'Annotation', icon: <Annotation /> },
  { label: 'AnnotationAlert', icon: <AnnotationAlert /> },
  { label: 'AnnotationCheck', icon: <AnnotationCheck /> },
  { label: 'AnnotationDots', icon: <AnnotationDots /> },
  { label: 'AnnotationHeart', icon: <AnnotationHeart /> },
  { label: 'AnnotationInfo', icon: <AnnotationInfo /> },
  { label: 'AnnotationPlus', icon: <AnnotationPlus /> },
  { label: 'AnnotationQuestion', icon: <AnnotationQuestion /> },
  { label: 'AnnotationX', icon: <AnnotationX /> },
  { label: 'Announcement01', icon: <Announcement01 /> },
  { label: 'Announcement02', icon: <Announcement02 /> },
  { label: 'Announcement03', icon: <Announcement03 /> },
  { label: 'Archive', icon: <Archive /> },
  { label: 'ArrowBlockDown', icon: <ArrowBlockDown /> },
  { label: 'ArrowBlockLeft', icon: <ArrowBlockLeft /> },
  { label: 'ArrowBlockRight', icon: <ArrowBlockRight /> },
  { label: 'ArrowBlockUp', icon: <ArrowBlockUp /> },
  { label: 'ArrowCircleBrokenDown', icon: <ArrowCircleBrokenDown /> },
  { label: 'ArrowCircleBrokenDownLeft', icon: <ArrowCircleBrokenDownLeft /> },
  { label: 'ArrowCircleBrokenDownRight', icon: <ArrowCircleBrokenDownRight /> },
  { label: 'ArrowCircleBrokenLeft', icon: <ArrowCircleBrokenLeft /> },
  { label: 'ArrowCircleBrokenRight', icon: <ArrowCircleBrokenRight /> },
  { label: 'ArrowCircleBrokenUp', icon: <ArrowCircleBrokenUp /> },
  { label: 'ArrowCircleBrokenUpLeft', icon: <ArrowCircleBrokenUpLeft /> },
  { label: 'ArrowCircleBrokenUpRight', icon: <ArrowCircleBrokenUpRight /> },
  { label: 'ArrowCircleDown', icon: <ArrowCircleDown /> },
  { label: 'ArrowCircleDownLeft', icon: <ArrowCircleDownLeft /> },
  { label: 'ArrowCircleDownRight', icon: <ArrowCircleDownRight /> },
  { label: 'ArrowCircleLeft', icon: <ArrowCircleLeft /> },
  { label: 'ArrowCircleRight', icon: <ArrowCircleRight /> },
  { label: 'ArrowCircleUp', icon: <ArrowCircleUp /> },
  { label: 'ArrowCircleUpLeft', icon: <ArrowCircleUpLeft /> },
  { label: 'ArrowCircleUpRight', icon: <ArrowCircleUpRight /> },
  { label: 'ArrowDown', icon: <ArrowDown /> },
  { label: 'ArrowDownLeft', icon: <ArrowDownLeft /> },
  { label: 'ArrowDownRight', icon: <ArrowDownRight /> },
  { label: 'ArrowLeft', icon: <ArrowLeft /> },
  { label: 'ArrowNarrowDown', icon: <ArrowNarrowDown /> },
  { label: 'ArrowNarrowDownLeft', icon: <ArrowNarrowDownLeft /> },
  { label: 'ArrowNarrowDownRight', icon: <ArrowNarrowDownRight /> },
  { label: 'ArrowNarrowLeft', icon: <ArrowNarrowLeft /> },
  { label: 'ArrowNarrowRight', icon: <ArrowNarrowRight /> },
  { label: 'ArrowNarrowUp', icon: <ArrowNarrowUp /> },
  { label: 'ArrowNarrowUpLeft', icon: <ArrowNarrowUpLeft /> },
  { label: 'ArrowNarrowUpRight', icon: <ArrowNarrowUpRight /> },
  { label: 'ArrowRight', icon: <ArrowRight /> },
  { label: 'ArrowSquareDown', icon: <ArrowSquareDown /> },
  { label: 'ArrowSquareDownLeft', icon: <ArrowSquareDownLeft /> },
  { label: 'ArrowSquareDownRight', icon: <ArrowSquareDownRight /> },
  { label: 'ArrowSquareLeft', icon: <ArrowSquareLeft /> },
  { label: 'ArrowSquareRight', icon: <ArrowSquareRight /> },
  { label: 'ArrowSquareUp', icon: <ArrowSquareUp /> },
  { label: 'ArrowSquareUpLeft', icon: <ArrowSquareUpLeft /> },
  { label: 'ArrowSquareUpRight', icon: <ArrowSquareUpRight /> },
  { label: 'ArrowUp', icon: <ArrowUp /> },
  { label: 'ArrowUpLeft', icon: <ArrowUpLeft /> },
  { label: 'ArrowUpRight', icon: <ArrowUpRight /> },
  { label: 'ArrowsDown', icon: <ArrowsDown /> },
  { label: 'ArrowsLeft', icon: <ArrowsLeft /> },
  { label: 'ArrowsRight', icon: <ArrowsRight /> },
  { label: 'ArrowsTriangle', icon: <ArrowsTriangle /> },
  { label: 'ArrowsUp', icon: <ArrowsUp /> },
  { label: 'Asterisk01', icon: <Asterisk01 /> },
  { label: 'Asterisk02', icon: <Asterisk02 /> },
  { label: 'AtSign', icon: <AtSign /> },
  { label: 'Atom01', icon: <Atom01 /> },
  { label: 'Atom02', icon: <Atom02 /> },
  { label: 'Attachment01', icon: <Attachment01 /> },
  { label: 'Attachment02', icon: <Attachment02 /> },
  { label: 'Award01', icon: <Award01 /> },
  { label: 'Award02', icon: <Award02 /> },
  { label: 'Award03', icon: <Award03 /> },
  { label: 'Award04', icon: <Award04 /> },
  { label: 'Award05', icon: <Award05 /> },
  { label: 'Backpack', icon: <Backpack /> },
  { label: 'Bank', icon: <Bank /> },
  { label: 'BankNote01', icon: <BankNote01 /> },
  { label: 'BankNote02', icon: <BankNote02 /> },
  { label: 'BankNote03', icon: <BankNote03 /> },
  { label: 'BarChart01', icon: <BarChart01 /> },
  { label: 'BarChart02', icon: <BarChart02 /> },
  { label: 'BarChart03', icon: <BarChart03 /> },
  { label: 'BarChart04', icon: <BarChart04 /> },
  { label: 'BarChart05', icon: <BarChart05 /> },
  { label: 'BarChart06', icon: <BarChart06 /> },
  { label: 'BarChart07', icon: <BarChart07 /> },
  { label: 'BarChart08', icon: <BarChart08 /> },
  { label: 'BarChart09', icon: <BarChart09 /> },
  { label: 'BarChart10', icon: <BarChart10 /> },
  { label: 'BarChart11', icon: <BarChart11 /> },
  { label: 'BarChart12', icon: <BarChart12 /> },
  { label: 'BarChartCircle01', icon: <BarChartCircle01 /> },
  { label: 'BarChartCircle02', icon: <BarChartCircle02 /> },
  { label: 'BarChartCircle03', icon: <BarChartCircle03 /> },
  { label: 'BarChartSquare01', icon: <BarChartSquare01 /> },
  { label: 'BarChartSquare02', icon: <BarChartSquare02 /> },
  { label: 'BarChartSquare03', icon: <BarChartSquare03 /> },
  { label: 'BarChartSquareDown', icon: <BarChartSquareDown /> },
  { label: 'BarChartSquareMinus', icon: <BarChartSquareMinus /> },
  { label: 'BarChartSquarePlus', icon: <BarChartSquarePlus /> },
  { label: 'BarChartSquareUp', icon: <BarChartSquareUp /> },
  { label: 'BarLineChart', icon: <BarLineChart /> },
  { label: 'BatteryCharging01', icon: <BatteryCharging01 /> },
  { label: 'BatteryCharging02', icon: <BatteryCharging02 /> },
  { label: 'BatteryEmpty', icon: <BatteryEmpty /> },
  { label: 'BatteryFull', icon: <BatteryFull /> },
  { label: 'BatteryLow', icon: <BatteryLow /> },
  { label: 'BatteryMid', icon: <BatteryMid /> },
  { label: 'Beaker01', icon: <Beaker01 /> },
  { label: 'Beaker02', icon: <Beaker02 /> },
  { label: 'Bell01', icon: <Bell01 /> },
  { label: 'Bell02', icon: <Bell02 /> },
  { label: 'Bell03', icon: <Bell03 /> },
  { label: 'Bell04', icon: <Bell04 /> },
  { label: 'BellMinus', icon: <BellMinus /> },
  { label: 'BellOff01', icon: <BellOff01 /> },
  { label: 'BellOff02', icon: <BellOff02 /> },
  { label: 'BellOff03', icon: <BellOff03 /> },
  { label: 'BellPlus', icon: <BellPlus /> },
  { label: 'BellRinging01', icon: <BellRinging01 /> },
  { label: 'BellRinging02', icon: <BellRinging02 /> },
  { label: 'BellRinging03', icon: <BellRinging03 /> },
  { label: 'BellRinging04', icon: <BellRinging04 /> },
  { label: 'BezierCurve01', icon: <BezierCurve01 /> },
  { label: 'BezierCurve02', icon: <BezierCurve02 /> },
  { label: 'BezierCurve03', icon: <BezierCurve03 /> },
  { label: 'BluetoothConnect', icon: <BluetoothConnect /> },
  { label: 'BluetoothOff', icon: <BluetoothOff /> },
  { label: 'BluetoothOn', icon: <BluetoothOn /> },
  { label: 'BluetoothSignal', icon: <BluetoothSignal /> },
  { label: 'Bold01', icon: <Bold01 /> },
  { label: 'Bold02', icon: <Bold02 /> },
  { label: 'BoldSquare', icon: <BoldSquare /> },
  { label: 'BookClosed', icon: <BookClosed /> },
  { label: 'BookOpen01', icon: <BookOpen01 /> },
  { label: 'BookOpen02', icon: <BookOpen02 /> },
  { label: 'Bookmark', icon: <Bookmark /> },
  { label: 'BookmarkAdd', icon: <BookmarkAdd /> },
  { label: 'BookmarkCheck', icon: <BookmarkCheck /> },
  { label: 'BookmarkMinus', icon: <BookmarkMinus /> },
  { label: 'BookmarkX', icon: <BookmarkX /> },
  { label: 'Box', icon: <Box /> },
  { label: 'Brackets', icon: <Brackets /> },
  { label: 'BracketsCheck', icon: <BracketsCheck /> },
  { label: 'BracketsEllipses', icon: <BracketsEllipses /> },
  { label: 'BracketsMinus', icon: <BracketsMinus /> },
  { label: 'BracketsPlus', icon: <BracketsPlus /> },
  { label: 'BracketsSlash', icon: <BracketsSlash /> },
  { label: 'BracketsX', icon: <BracketsX /> },
  { label: 'Briefcase01', icon: <Briefcase01 /> },
  { label: 'Briefcase02', icon: <Briefcase02 /> },
  { label: 'Browser', icon: <Browser /> },
  { label: 'Brush01', icon: <Brush01 /> },
  { label: 'Brush02', icon: <Brush02 /> },
  { label: 'Brush03', icon: <Brush03 /> },
  { label: 'Building01', icon: <Building01 /> },
  { label: 'Building02', icon: <Building02 /> },
  { label: 'Building03', icon: <Building03 /> },
  { label: 'Building04', icon: <Building04 /> },
  { label: 'Building05', icon: <Building05 /> },
  { label: 'Building06', icon: <Building06 /> },
  { label: 'Building07', icon: <Building07 /> },
  { label: 'Building08', icon: <Building08 /> },
  { label: 'Bus', icon: <Bus /> },
  { label: 'Calculator', icon: <Calculator /> },
  { label: 'Calendar', icon: <Calendar /> },
  { label: 'CalendarCheck01', icon: <CalendarCheck01 /> },
  { label: 'CalendarCheck02', icon: <CalendarCheck02 /> },
  { label: 'CalendarDate', icon: <CalendarDate /> },
  { label: 'CalendarHeart01', icon: <CalendarHeart01 /> },
  { label: 'CalendarHeart02', icon: <CalendarHeart02 /> },
  { label: 'CalendarMinus01', icon: <CalendarMinus01 /> },
  { label: 'CalendarMinus02', icon: <CalendarMinus02 /> },
  { label: 'CalendarPlus01', icon: <CalendarPlus01 /> },
  { label: 'CalendarPlus02', icon: <CalendarPlus02 /> },
  { label: 'Camera01', icon: <Camera01 /> },
  { label: 'Camera02', icon: <Camera02 /> },
  { label: 'Camera03', icon: <Camera03 /> },
  { label: 'CameraLens', icon: <CameraLens /> },
  { label: 'CameraOff', icon: <CameraOff /> },
  { label: 'CameraPlus', icon: <CameraPlus /> },
  { label: 'Certificate01', icon: <Certificate01 /> },
  { label: 'Certificate02', icon: <Certificate02 /> },
  { label: 'ChartBreakoutCircle', icon: <ChartBreakoutCircle /> },
  { label: 'ChartBreakoutSquare', icon: <ChartBreakoutSquare /> },
  { label: 'Check', icon: <Check /> },
  { label: 'CheckCircle', icon: <CheckCircle /> },
  { label: 'CheckCircleBroken', icon: <CheckCircleBroken /> },
  { label: 'CheckDone01', icon: <CheckDone01 /> },
  { label: 'CheckDone02', icon: <CheckDone02 /> },
  { label: 'CheckHeart', icon: <CheckHeart /> },
  { label: 'CheckSquare', icon: <CheckSquare /> },
  { label: 'CheckSquareBroken', icon: <CheckSquareBroken /> },
  { label: 'CheckVerified01', icon: <CheckVerified01 /> },
  { label: 'CheckVerified02', icon: <CheckVerified02 /> },
  { label: 'CheckVerified03', icon: <CheckVerified03 /> },
  { label: 'ChevronDown', icon: <ChevronDown /> },
  { label: 'ChevronDownDouble', icon: <ChevronDownDouble /> },
  { label: 'ChevronLeft', icon: <ChevronLeft /> },
  { label: 'ChevronLeftDouble', icon: <ChevronLeftDouble /> },
  { label: 'ChevronRight', icon: <ChevronRight /> },
  { label: 'ChevronRightDouble', icon: <ChevronRightDouble /> },
  { label: 'ChevronSelectorHorizontal', icon: <ChevronSelectorHorizontal /> },
  { label: 'ChevronSelectorVertical', icon: <ChevronSelectorVertical /> },
  { label: 'ChevronUp', icon: <ChevronUp /> },
  { label: 'ChevronUpDouble', icon: <ChevronUpDouble /> },
  { label: 'ChromeCast', icon: <ChromeCast /> },
  { label: 'Circle', icon: <Circle /> },
  { label: 'CircleCut', icon: <CircleCut /> },
  { label: 'Clapperboard', icon: <Clapperboard /> },
  { label: 'Clipboard', icon: <Clipboard /> },
  { label: 'ClipboardAttachment', icon: <ClipboardAttachment /> },
  { label: 'ClipboardCheck', icon: <ClipboardCheck /> },
  { label: 'ClipboardDownload', icon: <ClipboardDownload /> },
  { label: 'ClipboardMinus', icon: <ClipboardMinus /> },
  { label: 'ClipboardPlus', icon: <ClipboardPlus /> },
  { label: 'ClipboardX', icon: <ClipboardX /> },
  { label: 'Clock', icon: <Clock /> },
  { label: 'ClockCheck', icon: <ClockCheck /> },
  { label: 'ClockFastForward', icon: <ClockFastForward /> },
  { label: 'ClockPlus', icon: <ClockPlus /> },
  { label: 'ClockRefresh', icon: <ClockRefresh /> },
  { label: 'ClockRewind', icon: <ClockRewind /> },
  { label: 'ClockSnooze', icon: <ClockSnooze /> },
  { label: 'ClockStopwatch', icon: <ClockStopwatch /> },
  { label: 'Cloud01', icon: <Cloud01 /> },
  { label: 'Cloud02', icon: <Cloud02 /> },
  { label: 'Cloud03', icon: <Cloud03 /> },
  { label: 'CloudBlank01', icon: <CloudBlank01 /> },
  { label: 'CloudBlank02', icon: <CloudBlank02 /> },
  { label: 'CloudLightning', icon: <CloudLightning /> },
  { label: 'CloudMoon', icon: <CloudMoon /> },
  { label: 'CloudOff', icon: <CloudOff /> },
  { label: 'CloudRaining01', icon: <CloudRaining01 /> },
  { label: 'CloudRaining02', icon: <CloudRaining02 /> },
  { label: 'CloudRaining03', icon: <CloudRaining03 /> },
  { label: 'CloudRaining04', icon: <CloudRaining04 /> },
  { label: 'CloudRaining05', icon: <CloudRaining05 /> },
  { label: 'CloudRaining06', icon: <CloudRaining06 /> },
  { label: 'CloudSnowing01', icon: <CloudSnowing01 /> },
  { label: 'CloudSnowing02', icon: <CloudSnowing02 /> },
  { label: 'CloudSun01', icon: <CloudSun01 /> },
  { label: 'CloudSun02', icon: <CloudSun02 /> },
  { label: 'CloudSun03', icon: <CloudSun03 /> },
  { label: 'Code01', icon: <Code01 /> },
  { label: 'Code02', icon: <Code02 /> },
  { label: 'CodeBrowser', icon: <CodeBrowser /> },
  { label: 'CodeCircle01', icon: <CodeCircle01 /> },
  { label: 'CodeCircle02', icon: <CodeCircle02 /> },
  { label: 'CodeCircle03', icon: <CodeCircle03 /> },
  { label: 'CodeSnippet01', icon: <CodeSnippet01 /> },
  { label: 'CodeSnippet02', icon: <CodeSnippet02 /> },
  { label: 'CodeSquare01', icon: <CodeSquare01 /> },
  { label: 'CodeSquare02', icon: <CodeSquare02 /> },
  { label: 'Codepen', icon: <Codepen /> },
  { label: 'Coins01', icon: <Coins01 /> },
  { label: 'Coins02', icon: <Coins02 /> },
  { label: 'Coins03', icon: <Coins03 /> },
  { label: 'Coins04', icon: <Coins04 /> },
  { label: 'CoinsHand', icon: <CoinsHand /> },
  { label: 'CoinsStacked01', icon: <CoinsStacked01 /> },
  { label: 'CoinsStacked02', icon: <CoinsStacked02 /> },
  { label: 'CoinsStacked03', icon: <CoinsStacked03 /> },
  { label: 'CoinsStacked04', icon: <CoinsStacked04 /> },
  { label: 'CoinsSwap01', icon: <CoinsSwap01 /> },
  { label: 'CoinsSwap02', icon: <CoinsSwap02 /> },
  { label: 'Colors', icon: <Colors /> },
  { label: 'Columns01', icon: <Columns01 /> },
  { label: 'Columns02', icon: <Columns02 /> },
  { label: 'Columns03', icon: <Columns03 /> },
  { label: 'Command', icon: <Command /> },
  { label: 'Compass', icon: <Compass /> },
  { label: 'Compass01', icon: <Compass01 /> },
  { label: 'Compass02', icon: <Compass02 /> },
  { label: 'Compass03', icon: <Compass03 /> },
  { label: 'Container', icon: <Container /> },
  { label: 'Contrast01', icon: <Contrast01 /> },
  { label: 'Contrast02', icon: <Contrast02 /> },
  { label: 'Contrast03', icon: <Contrast03 /> },
  { label: 'Copy01', icon: <Copy01 /> },
  { label: 'Copy02', icon: <Copy02 /> },
  { label: 'Copy03', icon: <Copy03 /> },
  { label: 'Copy04', icon: <Copy04 /> },
  { label: 'Copy05', icon: <Copy05 /> },
  { label: 'Copy06', icon: <Copy06 /> },
  { label: 'Copy07', icon: <Copy07 /> },
  { label: 'CornerDownLeft', icon: <CornerDownLeft /> },
  { label: 'CornerDownRight', icon: <CornerDownRight /> },
  { label: 'CornerLeftDown', icon: <CornerLeftDown /> },
  { label: 'CornerLeftUp', icon: <CornerLeftUp /> },
  { label: 'CornerRightDown', icon: <CornerRightDown /> },
  { label: 'CornerRightUp', icon: <CornerRightUp /> },
  { label: 'CornerUpLeft', icon: <CornerUpLeft /> },
  { label: 'CornerUpRight', icon: <CornerUpRight /> },
  { label: 'CpuChip01', icon: <CpuChip01 /> },
  { label: 'CpuChip02', icon: <CpuChip02 /> },
  { label: 'CreditCard01', icon: <CreditCard01 /> },
  { label: 'CreditCard02', icon: <CreditCard02 /> },
  { label: 'CreditCardCheck', icon: <CreditCardCheck /> },
  { label: 'CreditCardDown', icon: <CreditCardDown /> },
  { label: 'CreditCardDownload', icon: <CreditCardDownload /> },
  { label: 'CreditCardEdit', icon: <CreditCardEdit /> },
  { label: 'CreditCardLock', icon: <CreditCardLock /> },
  { label: 'CreditCardMinus', icon: <CreditCardMinus /> },
  { label: 'CreditCardPlus', icon: <CreditCardPlus /> },
  { label: 'CreditCardRefresh', icon: <CreditCardRefresh /> },
  { label: 'CreditCardSearch', icon: <CreditCardSearch /> },
  { label: 'CreditCardShield', icon: <CreditCardShield /> },
  { label: 'CreditCardUp', icon: <CreditCardUp /> },
  { label: 'CreditCardUpload', icon: <CreditCardUpload /> },
  { label: 'CreditCardX', icon: <CreditCardX /> },
  { label: 'Crop01', icon: <Crop01 /> },
  { label: 'Crop02', icon: <Crop02 /> },
  { label: 'Cryptocurrency01', icon: <Cryptocurrency01 /> },
  { label: 'Cryptocurrency02', icon: <Cryptocurrency02 /> },
  { label: 'Cryptocurrency03', icon: <Cryptocurrency03 /> },
  { label: 'Cryptocurrency04', icon: <Cryptocurrency04 /> },
  { label: 'Cube01', icon: <Cube01 /> },
  { label: 'Cube02', icon: <Cube02 /> },
  { label: 'Cube03', icon: <Cube03 /> },
  { label: 'Cube04', icon: <Cube04 /> },
  { label: 'CubeOutline', icon: <CubeOutline /> },
  { label: 'CurrencyBitcoin', icon: <CurrencyBitcoin /> },
  { label: 'CurrencyBitcoinCircle', icon: <CurrencyBitcoinCircle /> },
  { label: 'CurrencyDollar', icon: <CurrencyDollar /> },
  { label: 'CurrencyDollarCircle', icon: <CurrencyDollarCircle /> },
  { label: 'CurrencyEthereum', icon: <CurrencyEthereum /> },
  { label: 'CurrencyEthereumCircle', icon: <CurrencyEthereumCircle /> },
  { label: 'CurrencyEuro', icon: <CurrencyEuro /> },
  { label: 'CurrencyEuroCircle', icon: <CurrencyEuroCircle /> },
  { label: 'CurrencyPound', icon: <CurrencyPound /> },
  { label: 'CurrencyPoundCircle', icon: <CurrencyPoundCircle /> },
  { label: 'CurrencyRuble', icon: <CurrencyRuble /> },
  { label: 'CurrencyRubleCircle', icon: <CurrencyRubleCircle /> },
  { label: 'CurrencyRupee', icon: <CurrencyRupee /> },
  { label: 'CurrencyRupeeCircle', icon: <CurrencyRupeeCircle /> },
  { label: 'CurrencyYen', icon: <CurrencyYen /> },
  { label: 'CurrencyYenCircle', icon: <CurrencyYenCircle /> },
  { label: 'Cursor01', icon: <Cursor01 /> },
  { label: 'Cursor02', icon: <Cursor02 /> },
  { label: 'Cursor03', icon: <Cursor03 /> },
  { label: 'Cursor04', icon: <Cursor04 /> },
  { label: 'CursorBox', icon: <CursorBox /> },
  { label: 'CursorClick01', icon: <CursorClick01 /> },
  { label: 'CursorClick02', icon: <CursorClick02 /> },
  { label: 'Data', icon: <Data /> },
  { label: 'Database01', icon: <Database01 /> },
  { label: 'Database02', icon: <Database02 /> },
  { label: 'Database03', icon: <Database03 /> },
  { label: 'Dataflow01', icon: <Dataflow01 /> },
  { label: 'Dataflow02', icon: <Dataflow02 /> },
  { label: 'Dataflow03', icon: <Dataflow03 /> },
  { label: 'Dataflow04', icon: <Dataflow04 /> },
  { label: 'Delete', icon: <Delete /> },
  { label: 'Diamond01', icon: <Diamond01 /> },
  { label: 'Diamond02', icon: <Diamond02 /> },
  { label: 'Dice1', icon: <Dice1 /> },
  { label: 'Dice2', icon: <Dice2 /> },
  { label: 'Dice3', icon: <Dice3 /> },
  { label: 'Dice4', icon: <Dice4 /> },
  { label: 'Dice5', icon: <Dice5 /> },
  { label: 'Dice6', icon: <Dice6 /> },
  { label: 'Disc01', icon: <Disc01 /> },
  { label: 'Disc02', icon: <Disc02 /> },
  { label: 'DistributeSpacingHorizontal', icon: <DistributeSpacingHorizontal /> },
  { label: 'DistributeSpacingVertical', icon: <DistributeSpacingVertical /> },
  { label: 'Divide01', icon: <Divide01 /> },
  { label: 'Divide02', icon: <Divide02 /> },
  { label: 'Divide03', icon: <Divide03 /> },
  { label: 'Divider', icon: <Divider /> },
  { label: 'Dotpoints01', icon: <Dotpoints01 /> },
  { label: 'Dotpoints02', icon: <Dotpoints02 /> },
  { label: 'DotsGrid', icon: <DotsGrid /> },
  { label: 'DotsHorizontal', icon: <DotsHorizontal /> },
  { label: 'DotsVertical', icon: <DotsVertical /> },
  { label: 'Download01', icon: <Download01 /> },
  { label: 'Download02', icon: <Download02 /> },
  { label: 'Download03', icon: <Download03 /> },
  { label: 'Download04', icon: <Download04 /> },
  { label: 'DownloadCloud01', icon: <DownloadCloud01 /> },
  { label: 'DownloadCloud02', icon: <DownloadCloud02 /> },
  { label: 'Drop', icon: <Drop /> },
  { label: 'Droplets01', icon: <Droplets01 /> },
  { label: 'Droplets02', icon: <Droplets02 /> },
  { label: 'Droplets03', icon: <Droplets03 /> },
  { label: 'Dropper', icon: <Dropper /> },
  { label: 'Edit01', icon: <Edit01 /> },
  { label: 'Edit02', icon: <Edit02 /> },
  { label: 'Edit03', icon: <Edit03 /> },
  { label: 'Edit04', icon: <Edit04 /> },
  { label: 'Edit05', icon: <Edit05 /> },
  { label: 'Equal', icon: <Equal /> },
  { label: 'EqualNot', icon: <EqualNot /> },
  { label: 'Eraser', icon: <Eraser /> },
  { label: 'Expand01', icon: <Expand01 /> },
  { label: 'Expand02', icon: <Expand02 /> },
  { label: 'Expand03', icon: <Expand03 /> },
  { label: 'Expand04', icon: <Expand04 /> },
  { label: 'Expand05', icon: <Expand05 /> },
  { label: 'Expand06', icon: <Expand06 /> },
  { label: 'Eye', icon: <Eye /> },
  { label: 'EyeOff', icon: <EyeOff /> },
  { label: 'FaceContent', icon: <FaceContent /> },
  { label: 'FaceFrown', icon: <FaceFrown /> },
  { label: 'FaceHappy', icon: <FaceHappy /> },
  { label: 'FaceId', icon: <FaceId /> },
  { label: 'FaceIdSquare', icon: <FaceIdSquare /> },
  { label: 'FaceNeutral', icon: <FaceNeutral /> },
  { label: 'FaceSad', icon: <FaceSad /> },
  { label: 'FaceSmile', icon: <FaceSmile /> },
  { label: 'FaceWink', icon: <FaceWink /> },
  { label: 'FastBackward', icon: <FastBackward /> },
  { label: 'FastForward', icon: <FastForward /> },
  { label: 'Feather', icon: <Feather /> },
  { label: 'Figma', icon: <Figma /> },
  { label: 'File01', icon: <File01 /> },
  { label: 'File02', icon: <File02 /> },
  { label: 'File03', icon: <File03 /> },
  { label: 'File04', icon: <File04 /> },
  { label: 'File05', icon: <File05 /> },
  { label: 'File06', icon: <File06 /> },
  { label: 'File07', icon: <File07 /> },
  { label: 'FileAttachment01', icon: <FileAttachment01 /> },
  { label: 'FileAttachment02', icon: <FileAttachment02 /> },
  { label: 'FileAttachment03', icon: <FileAttachment03 /> },
  { label: 'FileAttachment04', icon: <FileAttachment04 /> },
  { label: 'FileAttachment05', icon: <FileAttachment05 /> },
  { label: 'FileCheck01', icon: <FileCheck01 /> },
  { label: 'FileCheck02', icon: <FileCheck02 /> },
  { label: 'FileCheck03', icon: <FileCheck03 /> },
  { label: 'FileCode01', icon: <FileCode01 /> },
  { label: 'FileCode02', icon: <FileCode02 /> },
  { label: 'FileDownload01', icon: <FileDownload01 /> },
  { label: 'FileDownload02', icon: <FileDownload02 /> },
  { label: 'FileDownload03', icon: <FileDownload03 /> },
  { label: 'FileHeart01', icon: <FileHeart01 /> },
  { label: 'FileHeart02', icon: <FileHeart02 /> },
  { label: 'FileHeart03', icon: <FileHeart03 /> },
  { label: 'FileLock01', icon: <FileLock01 /> },
  { label: 'FileLock02', icon: <FileLock02 /> },
  { label: 'FileLock03', icon: <FileLock03 /> },
  { label: 'FileMinus01', icon: <FileMinus01 /> },
  { label: 'FileMinus02', icon: <FileMinus02 /> },
  { label: 'FileMinus03', icon: <FileMinus03 /> },
  { label: 'FilePlus01', icon: <FilePlus01 /> },
  { label: 'FilePlus02', icon: <FilePlus02 /> },
  { label: 'FilePlus03', icon: <FilePlus03 /> },
  { label: 'FileQuestion01', icon: <FileQuestion01 /> },
  { label: 'FileQuestion02', icon: <FileQuestion02 /> },
  { label: 'FileQuestion03', icon: <FileQuestion03 /> },
  { label: 'FileSearch01', icon: <FileSearch01 /> },
  { label: 'FileSearch02', icon: <FileSearch02 /> },
  { label: 'FileSearch03', icon: <FileSearch03 /> },
  { label: 'FileShield01', icon: <FileShield01 /> },
  { label: 'FileShield02', icon: <FileShield02 /> },
  { label: 'FileShield03', icon: <FileShield03 /> },
  { label: 'FileX01', icon: <FileX01 /> },
  { label: 'FileX02', icon: <FileX02 /> },
  { label: 'FileX03', icon: <FileX03 /> },
  { label: 'Film01', icon: <Film01 /> },
  { label: 'Film02', icon: <Film02 /> },
  { label: 'Film03', icon: <Film03 /> },
  { label: 'FilterFunnel01', icon: <FilterFunnel01 /> },
  { label: 'FilterFunnel02', icon: <FilterFunnel02 /> },
  { label: 'FilterLines', icon: <FilterLines /> },
  { label: 'Fingerprint01', icon: <Fingerprint01 /> },
  { label: 'Fingerprint02', icon: <Fingerprint02 /> },
  { label: 'Fingerprint03', icon: <Fingerprint03 /> },
  { label: 'Fingerprint04', icon: <Fingerprint04 /> },
  { label: 'Flag01', icon: <Flag01 /> },
  { label: 'Flag02', icon: <Flag02 /> },
  { label: 'Flag03', icon: <Flag03 /> },
  { label: 'Flag04', icon: <Flag04 /> },
  { label: 'Flag05', icon: <Flag05 /> },
  { label: 'Flag06', icon: <Flag06 /> },
  { label: 'Flash', icon: <Flash /> },
  { label: 'FlashOff', icon: <FlashOff /> },
  { label: 'FlexAlignBottom', icon: <FlexAlignBottom /> },
  { label: 'FlexAlignLeft', icon: <FlexAlignLeft /> },
  { label: 'FlexAlignRight', icon: <FlexAlignRight /> },
  { label: 'FlexAlignTop', icon: <FlexAlignTop /> },
  { label: 'FlipBackward', icon: <FlipBackward /> },
  { label: 'FlipForward', icon: <FlipForward /> },
  { label: 'Folder', icon: <Folder /> },
  { label: 'FolderCheck', icon: <FolderCheck /> },
  { label: 'FolderClosed', icon: <FolderClosed /> },
  { label: 'FolderCode', icon: <FolderCode /> },
  { label: 'FolderDownload', icon: <FolderDownload /> },
  { label: 'FolderLock', icon: <FolderLock /> },
  { label: 'FolderMinus', icon: <FolderMinus /> },
  { label: 'FolderPlus', icon: <FolderPlus /> },
  { label: 'FolderQuestion', icon: <FolderQuestion /> },
  { label: 'FolderSearch', icon: <FolderSearch /> },
  { label: 'FolderShield', icon: <FolderShield /> },
  { label: 'FolderX', icon: <FolderX /> },
  { label: 'Framer', icon: <Framer /> },
  { label: 'GamingPad01', icon: <GamingPad01 /> },
  { label: 'GamingPad02', icon: <GamingPad02 /> },
  { label: 'Gift01', icon: <Gift01 /> },
  { label: 'Gift02', icon: <Gift02 /> },
  { label: 'GitBranch01', icon: <GitBranch01 /> },
  { label: 'GitBranch02', icon: <GitBranch02 /> },
  { label: 'GitCommit', icon: <GitCommit /> },
  { label: 'GitMerge', icon: <GitMerge /> },
  { label: 'GitPullRequest', icon: <GitPullRequest /> },
  { label: 'Glasses01', icon: <Glasses01 /> },
  { label: 'Glasses02', icon: <Glasses02 /> },
  { label: 'Globe01', icon: <Globe01 /> },
  { label: 'Globe02', icon: <Globe02 /> },
  { label: 'Globe03', icon: <Globe03 /> },
  { label: 'Globe04', icon: <Globe04 /> },
  { label: 'Globe05', icon: <Globe05 /> },
  { label: 'Globe06', icon: <Globe06 /> },
  { label: 'GoogleChrome', icon: <GoogleChrome /> },
  { label: 'GraduationHat01', icon: <GraduationHat01 /> },
  { label: 'GraduationHat02', icon: <GraduationHat02 /> },
  { label: 'Grid01', icon: <Grid01 /> },
  { label: 'Grid02', icon: <Grid02 /> },
  { label: 'Grid03', icon: <Grid03 /> },
  { label: 'GridDotsBlank', icon: <GridDotsBlank /> },
  { label: 'GridDotsBottom', icon: <GridDotsBottom /> },
  { label: 'GridDotsHorizontalCenter', icon: <GridDotsHorizontalCenter /> },
  { label: 'GridDotsLeft', icon: <GridDotsLeft /> },
  { label: 'GridDotsOuter', icon: <GridDotsOuter /> },
  { label: 'GridDotsRight', icon: <GridDotsRight /> },
  { label: 'GridDotsTop', icon: <GridDotsTop /> },
  { label: 'GridDotsVerticalCenter', icon: <GridDotsVerticalCenter /> },
  { label: 'Hand', icon: <Hand /> },
  { label: 'HardDrive', icon: <HardDrive /> },
  { label: 'Hash01', icon: <Hash01 /> },
  { label: 'Hash02', icon: <Hash02 /> },
  { label: 'Heading01', icon: <Heading01 /> },
  { label: 'Heading02', icon: <Heading02 /> },
  { label: 'HeadingSquare', icon: <HeadingSquare /> },
  { label: 'Headphones01', icon: <Headphones01 /> },
  { label: 'Headphones02', icon: <Headphones02 /> },
  { label: 'Heart', icon: <Heart /> },
  { label: 'HeartCircle', icon: <HeartCircle /> },
  { label: 'HeartHand', icon: <HeartHand /> },
  { label: 'HeartHexagon', icon: <HeartHexagon /> },
  { label: 'HeartOctagon', icon: <HeartOctagon /> },
  { label: 'HeartRounded', icon: <HeartRounded /> },
  { label: 'HeartSquare', icon: <HeartSquare /> },
  { label: 'Hearts', icon: <Hearts /> },
  { label: 'HelpCircle', icon: <HelpCircle /> },
  { label: 'HelpOctagon', icon: <HelpOctagon /> },
  { label: 'HelpSquare', icon: <HelpSquare /> },
  { label: 'Hexagon01', icon: <Hexagon01 /> },
  { label: 'Hexagon02', icon: <Hexagon02 /> },
  { label: 'Home01', icon: <Home01 /> },
  { label: 'Home02', icon: <Home02 /> },
  { label: 'Home03', icon: <Home03 /> },
  { label: 'Home04', icon: <Home04 /> },
  { label: 'Home05', icon: <Home05 /> },
  { label: 'HomeLine', icon: <HomeLine /> },
  { label: 'HomeSmile', icon: <HomeSmile /> },
  { label: 'HorizontalBarChart01', icon: <HorizontalBarChart01 /> },
  { label: 'HorizontalBarChart02', icon: <HorizontalBarChart02 /> },
  { label: 'HorizontalBarChart03', icon: <HorizontalBarChart03 /> },
  { label: 'Hourglass01', icon: <Hourglass01 /> },
  { label: 'Hourglass02', icon: <Hourglass02 /> },
  { label: 'Hourglass03', icon: <Hourglass03 /> },
  { label: 'Hurricane01', icon: <Hurricane01 /> },
  { label: 'Hurricane02', icon: <Hurricane02 /> },
  { label: 'Hurricane03', icon: <Hurricane03 /> },
  { label: 'Image01', icon: <Image01 /> },
  { label: 'Image02', icon: <Image02 /> },
  { label: 'Image03', icon: <Image03 /> },
  { label: 'Image04', icon: <Image04 /> },
  { label: 'Image05', icon: <Image05 /> },
  { label: 'ImageCheck', icon: <ImageCheck /> },
  { label: 'ImageDown', icon: <ImageDown /> },
  { label: 'ImageIndentLeft', icon: <ImageIndentLeft /> },
  { label: 'ImageIndentRight', icon: <ImageIndentRight /> },
  { label: 'ImageLeft', icon: <ImageLeft /> },
  { label: 'ImagePlus', icon: <ImagePlus /> },
  { label: 'ImageRight', icon: <ImageRight /> },
  { label: 'ImageUp', icon: <ImageUp /> },
  { label: 'ImageUser', icon: <ImageUser /> },
  { label: 'ImageUserCheck', icon: <ImageUserCheck /> },
  { label: 'ImageUserDown', icon: <ImageUserDown /> },
  { label: 'ImageUserLeft', icon: <ImageUserLeft /> },
  { label: 'ImageUserPlus', icon: <ImageUserPlus /> },
  { label: 'ImageUserRight', icon: <ImageUserRight /> },
  { label: 'ImageUserUp', icon: <ImageUserUp /> },
  { label: 'ImageUserX', icon: <ImageUserX /> },
  { label: 'ImageX', icon: <ImageX /> },
  { label: 'Inbox01', icon: <Inbox01 /> },
  { label: 'Inbox02', icon: <Inbox02 /> },
  { label: 'Infinity', icon: <Infinity /> },
  { label: 'InfoCircle', icon: <InfoCircle /> },
  { label: 'InfoHexagon', icon: <InfoHexagon /> },
  { label: 'InfoOctagon', icon: <InfoOctagon /> },
  { label: 'InfoSquare', icon: <InfoSquare /> },
  { label: 'IntersectCircle', icon: <IntersectCircle /> },
  { label: 'IntersectSquare', icon: <IntersectSquare /> },
  { label: 'Italic01', icon: <Italic01 /> },
  { label: 'Italic02', icon: <Italic02 /> },
  { label: 'ItalicSquare', icon: <ItalicSquare /> },
  { label: 'Key01', icon: <Key01 /> },
  { label: 'Key02', icon: <Key02 /> },
  { label: 'Keyboard01', icon: <Keyboard01 /> },
  { label: 'Keyboard02', icon: <Keyboard02 /> },
  { label: 'Laptop01', icon: <Laptop01 /> },
  { label: 'Laptop02', icon: <Laptop02 /> },
  { label: 'LayerSingle', icon: <LayerSingle /> },
  { label: 'LayersThree01', icon: <LayersThree01 /> },
  { label: 'LayersThree02', icon: <LayersThree02 /> },
  { label: 'LayersTwo01', icon: <LayersTwo01 /> },
  { label: 'LayersTwo02', icon: <LayersTwo02 /> },
  { label: 'LayoutAlt01', icon: <LayoutAlt01 /> },
  { label: 'LayoutAlt02', icon: <LayoutAlt02 /> },
  { label: 'LayoutAlt03', icon: <LayoutAlt03 /> },
  { label: 'LayoutAlt04', icon: <LayoutAlt04 /> },
  { label: 'LayoutBottom', icon: <LayoutBottom /> },
  { label: 'LayoutGrid01', icon: <LayoutGrid01 /> },
  { label: 'LayoutGrid02', icon: <LayoutGrid02 /> },
  { label: 'LayoutLeft', icon: <LayoutLeft /> },
  { label: 'LayoutRight', icon: <LayoutRight /> },
  { label: 'LayoutTop', icon: <LayoutTop /> },
  { label: 'LeftIndent01', icon: <LeftIndent01 /> },
  { label: 'LeftIndent02', icon: <LeftIndent02 /> },
  { label: 'LetterSpacing01', icon: <LetterSpacing01 /> },
  { label: 'LetterSpacing02', icon: <LetterSpacing02 /> },
  { label: 'LifeBuoy01', icon: <LifeBuoy01 /> },
  { label: 'LifeBuoy02', icon: <LifeBuoy02 /> },
  { label: 'Lightbulb01', icon: <Lightbulb01 /> },
  { label: 'Lightbulb02', icon: <Lightbulb02 /> },
  { label: 'Lightbulb03', icon: <Lightbulb03 /> },
  { label: 'Lightbulb04', icon: <Lightbulb04 /> },
  { label: 'Lightbulb05', icon: <Lightbulb05 /> },
  { label: 'Lightning01', icon: <Lightning01 /> },
  { label: 'Lightning02', icon: <Lightning02 /> },
  { label: 'LineChartDown01', icon: <LineChartDown01 /> },
  { label: 'LineChartDown02', icon: <LineChartDown02 /> },
  { label: 'LineChartDown03', icon: <LineChartDown03 /> },
  { label: 'LineChartDown04', icon: <LineChartDown04 /> },
  { label: 'LineChartDown05', icon: <LineChartDown05 /> },
  { label: 'LineChartUp01', icon: <LineChartUp01 /> },
  { label: 'LineChartUp02', icon: <LineChartUp02 /> },
  { label: 'LineChartUp03', icon: <LineChartUp03 /> },
  { label: 'LineChartUp04', icon: <LineChartUp04 /> },
  { label: 'LineChartUp05', icon: <LineChartUp05 /> },
  { label: 'LineHeight', icon: <LineHeight /> },
  { label: 'Link01', icon: <Link01 /> },
  { label: 'Link02', icon: <Link02 /> },
  { label: 'Link03', icon: <Link03 /> },
  { label: 'Link04', icon: <Link04 /> },
  { label: 'Link05', icon: <Link05 /> },
  { label: 'LinkBroken01', icon: <LinkBroken01 /> },
  { label: 'LinkBroken02', icon: <LinkBroken02 /> },
  { label: 'LinkExternal01', icon: <LinkExternal01 /> },
  { label: 'LinkExternal02', icon: <LinkExternal02 /> },
  { label: 'List', icon: <List /> },
  { label: 'Loading01', icon: <Loading01 /> },
  { label: 'Loading02', icon: <Loading02 /> },
  { label: 'Loading03', icon: <Loading03 /> },
  { label: 'Lock01', icon: <Lock01 /> },
  { label: 'Lock02', icon: <Lock02 /> },
  { label: 'Lock03', icon: <Lock03 /> },
  { label: 'Lock04', icon: <Lock04 /> },
  { label: 'LockKeyholeCircle', icon: <LockKeyholeCircle /> },
  { label: 'LockKeyholeSquare', icon: <LockKeyholeSquare /> },
  { label: 'LockUnlocked01', icon: <LockUnlocked01 /> },
  { label: 'LockUnlocked02', icon: <LockUnlocked02 /> },
  { label: 'LockUnlocked03', icon: <LockUnlocked03 /> },
  { label: 'LockUnlocked04', icon: <LockUnlocked04 /> },
  { label: 'LogIn01', icon: <LogIn01 /> },
  { label: 'LogIn02', icon: <LogIn02 /> },
  { label: 'LogIn03', icon: <LogIn03 /> },
  { label: 'LogIn04', icon: <LogIn04 /> },
  { label: 'LogOut01', icon: <LogOut01 /> },
  { label: 'LogOut02', icon: <LogOut02 /> },
  { label: 'LogOut03', icon: <LogOut03 /> },
  { label: 'LogOut04', icon: <LogOut04 /> },
  { label: 'Luggage01', icon: <Luggage01 /> },
  { label: 'Luggage02', icon: <Luggage02 /> },
  { label: 'Luggage03', icon: <Luggage03 /> },
  { label: 'MagicWand01', icon: <MagicWand01 /> },
  { label: 'MagicWand02', icon: <MagicWand02 /> },
  { label: 'Mail01', icon: <Mail01 /> },
  { label: 'Mail02', icon: <Mail02 /> },
  { label: 'Mail03', icon: <Mail03 /> },
  { label: 'Mail04', icon: <Mail04 /> },
  { label: 'Mail05', icon: <Mail05 /> },
  { label: 'Map01', icon: <Map01 /> },
  { label: 'Map02', icon: <Map02 /> },
  { label: 'Mark', icon: <Mark /> },
  { label: 'MarkerPin01', icon: <MarkerPin01 /> },
  { label: 'MarkerPin02', icon: <MarkerPin02 /> },
  { label: 'MarkerPin03', icon: <MarkerPin03 /> },
  { label: 'MarkerPin04', icon: <MarkerPin04 /> },
  { label: 'MarkerPin05', icon: <MarkerPin05 /> },
  { label: 'MarkerPin06', icon: <MarkerPin06 /> },
  { label: 'Maximize01', icon: <Maximize01 /> },
  { label: 'Maximize02', icon: <Maximize02 /> },
  { label: 'MedicalCircle', icon: <MedicalCircle /> },
  { label: 'MedicalCross', icon: <MedicalCross /> },
  { label: 'MedicalSquare', icon: <MedicalSquare /> },
  { label: 'Menu01', icon: <Menu01 /> },
  { label: 'Menu02', icon: <Menu02 /> },
  { label: 'Menu03', icon: <Menu03 /> },
  { label: 'Menu04', icon: <Menu04 /> },
  { label: 'Menu05', icon: <Menu05 /> },
  { label: 'MessageAlertCircle', icon: <MessageAlertCircle /> },
  { label: 'MessageAlertSquare', icon: <MessageAlertSquare /> },
  { label: 'MessageChatCircle', icon: <MessageChatCircle /> },
  { label: 'MessageChatSquare', icon: <MessageChatSquare /> },
  { label: 'MessageCheckCircle', icon: <MessageCheckCircle /> },
  { label: 'MessageCheckSquare', icon: <MessageCheckSquare /> },
  { label: 'MessageCircle01', icon: <MessageCircle01 /> },
  { label: 'MessageCircle02', icon: <MessageCircle02 /> },
  { label: 'MessageDotsCircle', icon: <MessageDotsCircle /> },
  { label: 'MessageDotsSquare', icon: <MessageDotsSquare /> },
  { label: 'MessageHeartCircle', icon: <MessageHeartCircle /> },
  { label: 'MessageHeartSquare', icon: <MessageHeartSquare /> },
  { label: 'MessageNotificationCircle', icon: <MessageNotificationCircle /> },
  { label: 'MessageNotificationSquare', icon: <MessageNotificationSquare /> },
  { label: 'MessagePlusCircle', icon: <MessagePlusCircle /> },
  { label: 'MessagePlusSquare', icon: <MessagePlusSquare /> },
  { label: 'MessageQuestionCircle', icon: <MessageQuestionCircle /> },
  { label: 'MessageQuestionSquare', icon: <MessageQuestionSquare /> },
  { label: 'MessageSmileCircle', icon: <MessageSmileCircle /> },
  { label: 'MessageSmileSquare', icon: <MessageSmileSquare /> },
  { label: 'MessageSquare01', icon: <MessageSquare01 /> },
  { label: 'MessageSquare02', icon: <MessageSquare02 /> },
  { label: 'MessageTextCircle01', icon: <MessageTextCircle01 /> },
  { label: 'MessageTextCircle02', icon: <MessageTextCircle02 /> },
  { label: 'MessageTextSquare01', icon: <MessageTextSquare01 /> },
  { label: 'MessageTextSquare02', icon: <MessageTextSquare02 /> },
  { label: 'MessageXCircle', icon: <MessageXCircle /> },
  { label: 'MessageXSquare', icon: <MessageXSquare /> },
  { label: 'Microphone01', icon: <Microphone01 /> },
  { label: 'Microphone02', icon: <Microphone02 /> },
  { label: 'MicrophoneOff01', icon: <MicrophoneOff01 /> },
  { label: 'MicrophoneOff02', icon: <MicrophoneOff02 /> },
  { label: 'Microscope', icon: <Microscope /> },
  { label: 'Minimize01', icon: <Minimize01 /> },
  { label: 'Minimize02', icon: <Minimize02 /> },
  { label: 'Minus', icon: <Minus /> },
  { label: 'MinusCircle', icon: <MinusCircle /> },
  { label: 'MinusSquare', icon: <MinusSquare /> },
  { label: 'Modem01', icon: <Modem01 /> },
  { label: 'Modem02', icon: <Modem02 /> },
  { label: 'Monitor01', icon: <Monitor01 /> },
  { label: 'Monitor02', icon: <Monitor02 /> },
  { label: 'Monitor03', icon: <Monitor03 /> },
  { label: 'Monitor04', icon: <Monitor04 /> },
  { label: 'Monitor05', icon: <Monitor05 /> },
  { label: 'Moon01', icon: <Moon01 /> },
  { label: 'Moon02', icon: <Moon02 /> },
  { label: 'MoonEclipse', icon: <MoonEclipse /> },
  { label: 'MoonStar', icon: <MoonStar /> },
  { label: 'Mouse', icon: <Mouse /> },
  { label: 'Move', icon: <Move /> },
  { label: 'MusicNote01', icon: <MusicNote01 /> },
  { label: 'MusicNote02', icon: <MusicNote02 /> },
  { label: 'MusicNotePlus', icon: <MusicNotePlus /> },
  { label: 'NavigationPointer01', icon: <NavigationPointer01 /> },
  { label: 'NavigationPointer02', icon: <NavigationPointer02 /> },
  { label: 'NavigationPointerOff01', icon: <NavigationPointerOff01 /> },
  { label: 'NavigationPointerOff02', icon: <NavigationPointerOff02 /> },
  { label: 'NotificationBox', icon: <NotificationBox /> },
  { label: 'NotificationMessage', icon: <NotificationMessage /> },
  { label: 'NotificationText', icon: <NotificationText /> },
  { label: 'Octagon', icon: <Octagon /> },
  { label: 'Package', icon: <Package /> },
  { label: 'PackageCheck', icon: <PackageCheck /> },
  { label: 'PackageMinus', icon: <PackageMinus /> },
  { label: 'PackagePlus', icon: <PackagePlus /> },
  { label: 'PackageSearch', icon: <PackageSearch /> },
  { label: 'PackageX', icon: <PackageX /> },
  { label: 'Paint', icon: <Paint /> },
  { label: 'PaintPour', icon: <PaintPour /> },
  { label: 'Palette', icon: <Palette /> },
  { label: 'Paperclip', icon: <Paperclip /> },
  { label: 'ParagraphSpacing', icon: <ParagraphSpacing /> },
  { label: 'ParagraphWrap', icon: <ParagraphWrap /> },
  { label: 'Passcode', icon: <Passcode /> },
  { label: 'PasscodeLock', icon: <PasscodeLock /> },
  { label: 'Passport', icon: <Passport /> },
  { label: 'PauseCircle', icon: <PauseCircle /> },
  { label: 'PauseSquare', icon: <PauseSquare /> },
  { label: 'PenTool01', icon: <PenTool01 /> },
  { label: 'PenTool02', icon: <PenTool02 /> },
  { label: 'PenToolMinus', icon: <PenToolMinus /> },
  { label: 'PenToolPlus', icon: <PenToolPlus /> },
  { label: 'Pencil01', icon: <Pencil01 /> },
  { label: 'Pencil02', icon: <Pencil02 /> },
  { label: 'PencilLine', icon: <PencilLine /> },
  { label: 'Pentagon', icon: <Pentagon /> },
  { label: 'Percent01', icon: <Percent01 /> },
  { label: 'Percent02', icon: <Percent02 /> },
  { label: 'Percent03', icon: <Percent03 /> },
  { label: 'Perspective01', icon: <Perspective01 /> },
  { label: 'Perspective02', icon: <Perspective02 /> },
  { label: 'Phone', icon: <Phone /> },
  { label: 'Phone01', icon: <Phone01 /> },
  { label: 'Phone02', icon: <Phone02 /> },
  { label: 'PhoneCall01', icon: <PhoneCall01 /> },
  { label: 'PhoneCall02', icon: <PhoneCall02 /> },
  { label: 'PhoneHangUp', icon: <PhoneHangUp /> },
  { label: 'PhoneIncoming01', icon: <PhoneIncoming01 /> },
  { label: 'PhoneIncoming02', icon: <PhoneIncoming02 /> },
  { label: 'PhoneOutgoing01', icon: <PhoneOutgoing01 /> },
  { label: 'PhoneOutgoing02', icon: <PhoneOutgoing02 /> },
  { label: 'PhonePause', icon: <PhonePause /> },
  { label: 'PhonePlus', icon: <PhonePlus /> },
  { label: 'PhoneX', icon: <PhoneX /> },
  { label: 'PieChart01', icon: <PieChart01 /> },
  { label: 'PieChart02', icon: <PieChart02 /> },
  { label: 'PieChart03', icon: <PieChart03 /> },
  { label: 'PieChart04', icon: <PieChart04 /> },
  { label: 'PiggyBank01', icon: <PiggyBank01 /> },
  { label: 'PiggyBank02', icon: <PiggyBank02 /> },
  { label: 'Pilcrow01', icon: <Pilcrow01 /> },
  { label: 'Pilcrow02', icon: <Pilcrow02 /> },
  { label: 'PilcrowSquare', icon: <PilcrowSquare /> },
  { label: 'Pin01', icon: <Pin01 /> },
  { label: 'Pin02', icon: <Pin02 /> },
  { label: 'Placeholder', icon: <Placeholder /> },
  { label: 'Plane', icon: <Plane /> },
  { label: 'Play', icon: <Play /> },
  { label: 'PlayCircle', icon: <PlayCircle /> },
  { label: 'PlaySquare', icon: <PlaySquare /> },
  { label: 'Plus', icon: <Plus /> },
  { label: 'PlusCircle', icon: <PlusCircle /> },
  { label: 'PlusSquare', icon: <PlusSquare /> },
  { label: 'Podcast', icon: <Podcast /> },
  { label: 'Power01', icon: <Power01 /> },
  { label: 'Power02', icon: <Power02 /> },
  { label: 'Power03', icon: <Power03 /> },
  { label: 'PresentationChart01', icon: <PresentationChart01 /> },
  { label: 'PresentationChart02', icon: <PresentationChart02 /> },
  { label: 'PresentationChart03', icon: <PresentationChart03 /> },
  { label: 'Printer', icon: <Printer /> },
  { label: 'PuzzlePiece01', icon: <PuzzlePiece01 /> },
  { label: 'PuzzlePiece02', icon: <PuzzlePiece02 /> },
  { label: 'QrCode01', icon: <QrCode01 /> },
  { label: 'QrCode02', icon: <QrCode02 /> },
  { label: 'Receipt', icon: <Receipt /> },
  { label: 'ReceiptCheck', icon: <ReceiptCheck /> },
  { label: 'Recording01', icon: <Recording01 /> },
  { label: 'Recording02', icon: <Recording02 /> },
  { label: 'Recording03', icon: <Recording03 /> },
  { label: 'Reflect01', icon: <Reflect01 /> },
  { label: 'Reflect02', icon: <Reflect02 /> },
  { label: 'RefreshCcw01', icon: <RefreshCcw01 /> },
  { label: 'RefreshCcw02', icon: <RefreshCcw02 /> },
  { label: 'RefreshCcw03', icon: <RefreshCcw03 /> },
  { label: 'RefreshCcw04', icon: <RefreshCcw04 /> },
  { label: 'RefreshCcw05', icon: <RefreshCcw05 /> },
  { label: 'RefreshCw01', icon: <RefreshCw01 /> },
  { label: 'RefreshCw02', icon: <RefreshCw02 /> },
  { label: 'RefreshCw03', icon: <RefreshCw03 /> },
  { label: 'RefreshCw04', icon: <RefreshCw04 /> },
  { label: 'RefreshCw05', icon: <RefreshCw05 /> },
  { label: 'Repeat01', icon: <Repeat01 /> },
  { label: 'Repeat02', icon: <Repeat02 /> },
  { label: 'Repeat03', icon: <Repeat03 /> },
  { label: 'Repeat04', icon: <Repeat04 /> },
  { label: 'ReverseLeft', icon: <ReverseLeft /> },
  { label: 'ReverseRight', icon: <ReverseRight /> },
  { label: 'RightIndent01', icon: <RightIndent01 /> },
  { label: 'RightIndent02', icon: <RightIndent02 /> },
  { label: 'Rocket01', icon: <Rocket01 /> },
  { label: 'Rocket02', icon: <Rocket02 /> },
  { label: 'RollerBrush', icon: <RollerBrush /> },
  { label: 'Route', icon: <Route /> },
  { label: 'Rows01', icon: <Rows01 /> },
  { label: 'Rows02', icon: <Rows02 /> },
  { label: 'Rows03', icon: <Rows03 /> },
  { label: 'Rss01', icon: <Rss01 /> },
  { label: 'Rss02', icon: <Rss02 /> },
  { label: 'Ruler', icon: <Ruler /> },
  { label: 'Safe', icon: <Safe /> },
  { label: 'Sale01', icon: <Sale01 /> },
  { label: 'Sale02', icon: <Sale02 /> },
  { label: 'Sale03', icon: <Sale03 /> },
  { label: 'Sale04', icon: <Sale04 /> },
  { label: 'Save01', icon: <Save01 /> },
  { label: 'Save02', icon: <Save02 /> },
  { label: 'Save03', icon: <Save03 /> },
  { label: 'Scale01', icon: <Scale01 /> },
  { label: 'Scale02', icon: <Scale02 /> },
  { label: 'Scale03', icon: <Scale03 /> },
  { label: 'Scales01', icon: <Scales01 /> },
  { label: 'Scales02', icon: <Scales02 /> },
  { label: 'Scan', icon: <Scan /> },
  { label: 'Scissors01', icon: <Scissors01 /> },
  { label: 'Scissors02', icon: <Scissors02 /> },
  { label: 'ScissorsCut01', icon: <ScissorsCut01 /> },
  { label: 'ScissorsCut02', icon: <ScissorsCut02 /> },
  { label: 'SearchLg', icon: <SearchLg /> },
  { label: 'SearchMd', icon: <SearchMd /> },
  { label: 'SearchRefraction', icon: <SearchRefraction /> },
  { label: 'SearchSm', icon: <SearchSm /> },
  { label: 'Send01', icon: <Send01 /> },
  { label: 'Send02', icon: <Send02 /> },
  { label: 'Send03', icon: <Send03 /> },
  { label: 'Server01', icon: <Server01 /> },
  { label: 'Server02', icon: <Server02 /> },
  { label: 'Server03', icon: <Server03 /> },
  { label: 'Server04', icon: <Server04 /> },
  { label: 'Server05', icon: <Server05 /> },
  { label: 'Server06', icon: <Server06 /> },
  { label: 'Settings01', icon: <Settings01 /> },
  { label: 'Settings02', icon: <Settings02 /> },
  { label: 'Settings03', icon: <Settings03 /> },
  { label: 'Settings04', icon: <Settings04 /> },
  { label: 'Share01', icon: <Share01 /> },
  { label: 'Share02', icon: <Share02 /> },
  { label: 'Share03', icon: <Share03 /> },
  { label: 'Share04', icon: <Share04 /> },
  { label: 'Share05', icon: <Share05 /> },
  { label: 'Share06', icon: <Share06 /> },
  { label: 'Share07', icon: <Share07 /> },
  { label: 'Shield01', icon: <Shield01 /> },
  { label: 'Shield02', icon: <Shield02 /> },
  { label: 'Shield03', icon: <Shield03 /> },
  { label: 'ShieldDollar', icon: <ShieldDollar /> },
  { label: 'ShieldOff', icon: <ShieldOff /> },
  { label: 'ShieldPlus', icon: <ShieldPlus /> },
  { label: 'ShieldTick', icon: <ShieldTick /> },
  { label: 'ShieldZap', icon: <ShieldZap /> },
  { label: 'ShoppingBag01', icon: <ShoppingBag01 /> },
  { label: 'ShoppingBag02', icon: <ShoppingBag02 /> },
  { label: 'ShoppingBag03', icon: <ShoppingBag03 /> },
  { label: 'ShoppingCart01', icon: <ShoppingCart01 /> },
  { label: 'ShoppingCart02', icon: <ShoppingCart02 /> },
  { label: 'ShoppingCart03', icon: <ShoppingCart03 /> },
  { label: 'Shuffle01', icon: <Shuffle01 /> },
  { label: 'Shuffle02', icon: <Shuffle02 /> },
  { label: 'Signal01', icon: <Signal01 /> },
  { label: 'Signal02', icon: <Signal02 /> },
  { label: 'Signal03', icon: <Signal03 /> },
  { label: 'Simcard', icon: <Simcard /> },
  { label: 'Skew', icon: <Skew /> },
  { label: 'SkipBack', icon: <SkipBack /> },
  { label: 'SkipForward', icon: <SkipForward /> },
  { label: 'SlashCircle01', icon: <SlashCircle01 /> },
  { label: 'SlashCircle02', icon: <SlashCircle02 /> },
  { label: 'SlashDivider', icon: <SlashDivider /> },
  { label: 'SlashOctagon', icon: <SlashOctagon /> },
  { label: 'Sliders01', icon: <Sliders01 /> },
  { label: 'Sliders02', icon: <Sliders02 /> },
  { label: 'Sliders03', icon: <Sliders03 /> },
  { label: 'Sliders04', icon: <Sliders04 /> },
  { label: 'Snowflake01', icon: <Snowflake01 /> },
  { label: 'Snowflake02', icon: <Snowflake02 /> },
  { label: 'SpacingHeight01', icon: <SpacingHeight01 /> },
  { label: 'SpacingHeight02', icon: <SpacingHeight02 /> },
  { label: 'SpacingWidth01', icon: <SpacingWidth01 /> },
  { label: 'SpacingWidth02', icon: <SpacingWidth02 /> },
  { label: 'Speaker01', icon: <Speaker01 /> },
  { label: 'Speaker02', icon: <Speaker02 /> },
  { label: 'Speaker03', icon: <Speaker03 /> },
  { label: 'Speedometer01', icon: <Speedometer01 /> },
  { label: 'Speedometer02', icon: <Speedometer02 /> },
  { label: 'Speedometer03', icon: <Speedometer03 /> },
  { label: 'Speedometer04', icon: <Speedometer04 /> },
  { label: 'Square', icon: <Square /> },
  { label: 'Stand', icon: <Stand /> },
  { label: 'Star01', icon: <Star01 /> },
  { label: 'Star02', icon: <Star02 /> },
  { label: 'Star03', icon: <Star03 /> },
  { label: 'Star04', icon: <Star04 /> },
  { label: 'Star05', icon: <Star05 /> },
  { label: 'Star06', icon: <Star06 /> },
  { label: 'Star07', icon: <Star07 /> },
  { label: 'Stars01', icon: <Stars01 /> },
  { label: 'Stars02', icon: <Stars02 /> },
  { label: 'Stars03', icon: <Stars03 /> },
  { label: 'StickerCircle', icon: <StickerCircle /> },
  { label: 'StickerSquare', icon: <StickerSquare /> },
  { label: 'Stop', icon: <Stop /> },
  { label: 'StopCircle', icon: <StopCircle /> },
  { label: 'StopSquare', icon: <StopSquare /> },
  { label: 'Strikethrough01', icon: <Strikethrough01 /> },
  { label: 'Strikethrough02', icon: <Strikethrough02 /> },
  { label: 'StrikethroughSquare', icon: <StrikethroughSquare /> },
  { label: 'Subscript', icon: <Subscript /> },
  { label: 'Sun', icon: <Sun /> },
  { label: 'SunSetting01', icon: <SunSetting01 /> },
  { label: 'SunSetting02', icon: <SunSetting02 /> },
  { label: 'SunSetting03', icon: <SunSetting03 /> },
  { label: 'Sunrise', icon: <Sunrise /> },
  { label: 'Sunset', icon: <Sunset /> },
  { label: 'SwitchHorizontal01', icon: <SwitchHorizontal01 /> },
  { label: 'SwitchHorizontal02', icon: <SwitchHorizontal02 /> },
  { label: 'SwitchVertical01', icon: <SwitchVertical01 /> },
  { label: 'SwitchVertical02', icon: <SwitchVertical02 /> },
  { label: 'Table', icon: <Table /> },
  { label: 'Tablet01', icon: <Tablet01 /> },
  { label: 'Tablet02', icon: <Tablet02 /> },
  { label: 'Tag01', icon: <Tag01 /> },
  { label: 'Tag02', icon: <Tag02 /> },
  { label: 'Tag03', icon: <Tag03 /> },
  { label: 'Target01', icon: <Target01 /> },
  { label: 'Target02', icon: <Target02 /> },
  { label: 'Target03', icon: <Target03 /> },
  { label: 'Target04', icon: <Target04 /> },
  { label: 'Target05', icon: <Target05 /> },
  { label: 'Telescope', icon: <Telescope /> },
  { label: 'Terminal', icon: <Terminal /> },
  { label: 'TerminalBrowser', icon: <TerminalBrowser /> },
  { label: 'TerminalCircle', icon: <TerminalCircle /> },
  { label: 'TerminalSquare', icon: <TerminalSquare /> },
  { label: 'TextInput', icon: <TextInput /> },
  { label: 'Thermometer01', icon: <Thermometer01 /> },
  { label: 'Thermometer02', icon: <Thermometer02 /> },
  { label: 'Thermometer03', icon: <Thermometer03 /> },
  { label: 'ThermometerCold', icon: <ThermometerCold /> },
  { label: 'ThermometerWarm', icon: <ThermometerWarm /> },
  { label: 'ThumbsDown', icon: <ThumbsDown /> },
  { label: 'ThumbsUp', icon: <ThumbsUp /> },
  { label: 'Ticket01', icon: <Ticket01 /> },
  { label: 'Ticket02', icon: <Ticket02 /> },
  { label: 'Toggle01Left', icon: <Toggle01Left /> },
  { label: 'Toggle01Right', icon: <Toggle01Right /> },
  { label: 'Toggle02Left', icon: <Toggle02Left /> },
  { label: 'Toggle02Right', icon: <Toggle02Right /> },
  { label: 'Toggle03Left', icon: <Toggle03Left /> },
  { label: 'Toggle03Right', icon: <Toggle03Right /> },
  { label: 'Tool01', icon: <Tool01 /> },
  { label: 'Tool02', icon: <Tool02 /> },
  { label: 'Train', icon: <Train /> },
  { label: 'Tram', icon: <Tram /> },
  { label: 'Transform', icon: <Transform /> },
  { label: 'Translate01', icon: <Translate01 /> },
  { label: 'Translate02', icon: <Translate02 /> },
  { label: 'Trash01', icon: <Trash01 /> },
  { label: 'Trash02', icon: <Trash02 /> },
  { label: 'Trash03', icon: <Trash03 /> },
  { label: 'Trash04', icon: <Trash04 /> },
  { label: 'TrendDown01', icon: <TrendDown01 /> },
  { label: 'TrendDown02', icon: <TrendDown02 /> },
  { label: 'TrendUp01', icon: <TrendUp01 /> },
  { label: 'TrendUp02', icon: <TrendUp02 /> },
  { label: 'Triangle', icon: <Triangle /> },
  { label: 'Trophy01', icon: <Trophy01 /> },
  { label: 'Trophy02', icon: <Trophy02 /> },
  { label: 'Truck01', icon: <Truck01 /> },
  { label: 'Truck02', icon: <Truck02 /> },
  { label: 'Tv01', icon: <Tv01 /> },
  { label: 'Tv02', icon: <Tv02 /> },
  { label: 'Tv03', icon: <Tv03 /> },
  { label: 'Type01', icon: <Type01 /> },
  { label: 'Type02', icon: <Type02 /> },
  { label: 'TypeSquare', icon: <TypeSquare /> },
  { label: 'TypeStrikethrough01', icon: <TypeStrikethrough01 /> },
  { label: 'TypeStrikethrough02', icon: <TypeStrikethrough02 /> },
  { label: 'Umbrella01', icon: <Umbrella01 /> },
  { label: 'Umbrella02', icon: <Umbrella02 /> },
  { label: 'Umbrella03', icon: <Umbrella03 /> },
  { label: 'Underline01', icon: <Underline01 /> },
  { label: 'Underline02', icon: <Underline02 /> },
  { label: 'UnderlineSquare', icon: <UnderlineSquare /> },
  { label: 'Upload01', icon: <Upload01 /> },
  { label: 'Upload02', icon: <Upload02 /> },
  { label: 'Upload03', icon: <Upload03 /> },
  { label: 'Upload04', icon: <Upload04 /> },
  { label: 'UploadCloud01', icon: <UploadCloud01 /> },
  { label: 'UploadCloud02', icon: <UploadCloud02 /> },
  { label: 'UsbFlashDrive', icon: <UsbFlashDrive /> },
  { label: 'User01', icon: <User01 /> },
  { label: 'User02', icon: <User02 /> },
  { label: 'User03', icon: <User03 /> },
  { label: 'UserCheck01', icon: <UserCheck01 /> },
  { label: 'UserCheck02', icon: <UserCheck02 /> },
  { label: 'UserCircle', icon: <UserCircle /> },
  { label: 'UserDown01', icon: <UserDown01 /> },
  { label: 'UserDown02', icon: <UserDown02 /> },
  { label: 'UserEdit', icon: <UserEdit /> },
  { label: 'UserLeft01', icon: <UserLeft01 /> },
  { label: 'UserLeft02', icon: <UserLeft02 /> },
  { label: 'UserMinus01', icon: <UserMinus01 /> },
  { label: 'UserMinus02', icon: <UserMinus02 /> },
  { label: 'UserPlus01', icon: <UserPlus01 /> },
  { label: 'UserPlus02', icon: <UserPlus02 /> },
  { label: 'UserRight01', icon: <UserRight01 /> },
  { label: 'UserRight02', icon: <UserRight02 /> },
  { label: 'UserSquare', icon: <UserSquare /> },
  { label: 'UserUp01', icon: <UserUp01 /> },
  { label: 'UserUp02', icon: <UserUp02 /> },
  { label: 'UserX01', icon: <UserX01 /> },
  { label: 'UserX02', icon: <UserX02 /> },
  { label: 'Users01', icon: <Users01 /> },
  { label: 'Users02', icon: <Users02 /> },
  { label: 'Users03', icon: <Users03 /> },
  { label: 'UsersCheck', icon: <UsersCheck /> },
  { label: 'UsersDown', icon: <UsersDown /> },
  { label: 'UsersEdit', icon: <UsersEdit /> },
  { label: 'UsersLeft', icon: <UsersLeft /> },
  { label: 'UsersMinus', icon: <UsersMinus /> },
  { label: 'UsersPlus', icon: <UsersPlus /> },
  { label: 'UsersRight', icon: <UsersRight /> },
  { label: 'UsersUp', icon: <UsersUp /> },
  { label: 'UsersX', icon: <UsersX /> },
  { label: 'Variable', icon: <Variable /> },
  { label: 'VideoRecorder', icon: <VideoRecorder /> },
  { label: 'VideoRecorderOff', icon: <VideoRecorderOff /> },
  { label: 'Virus', icon: <Virus /> },
  { label: 'Voicemail', icon: <Voicemail /> },
  { label: 'VolumeMax', icon: <VolumeMax /> },
  { label: 'VolumeMin', icon: <VolumeMin /> },
  { label: 'VolumeMinus', icon: <VolumeMinus /> },
  { label: 'VolumePlus', icon: <VolumePlus /> },
  { label: 'VolumeX', icon: <VolumeX /> },
  { label: 'Wallet01', icon: <Wallet01 /> },
  { label: 'Wallet02', icon: <Wallet02 /> },
  { label: 'Wallet03', icon: <Wallet03 /> },
  { label: 'Wallet04', icon: <Wallet04 /> },
  { label: 'Wallet05', icon: <Wallet05 /> },
  { label: 'WatchCircle', icon: <WatchCircle /> },
  { label: 'WatchSquare', icon: <WatchSquare /> },
  { label: 'Waves', icon: <Waves /> },
  { label: 'Webcam01', icon: <Webcam01 /> },
  { label: 'Webcam02', icon: <Webcam02 /> },
  { label: 'Wifi', icon: <Wifi /> },
  { label: 'WifiOff', icon: <WifiOff /> },
  { label: 'Wind01', icon: <Wind01 /> },
  { label: 'Wind02', icon: <Wind02 /> },
  { label: 'Wind03', icon: <Wind03 /> },
  { label: 'X', icon: <X /> },
  { label: 'XCircle', icon: <XCircle /> },
  { label: 'XClose', icon: <XClose /> },
  { label: 'XSquare', icon: <XSquare /> },
  { label: 'Youtube', icon: <Youtube /> },
  { label: 'Zap', icon: <Zap /> },
  { label: 'ZapCircle', icon: <ZapCircle /> },
  { label: 'ZapFast', icon: <ZapFast /> },
  { label: 'ZapOff', icon: <ZapOff /> },
  { label: 'ZapSquare', icon: <ZapSquare /> },
  { label: 'ZoomIn', icon: <ZoomIn /> },
  { label: 'ZoomOut', icon: <ZoomOut /> },
]
const IconsPage = () => {
  return (
    <>
      <div className="border-bottom flex">
        <h3>Untitled UI Icons Library</h3>
        v0.1.3
      </div>
      <div className="flex-icon">
        {icons.map((item, i) => {
          return (
            <div className="canvas-card-2 flex" key={i} style={{ width: '25%' }}>
              {item.icon} <p>{item.label}</p>
            </div>
          )
        })}
      </div>
    </>
  )
}

export default IconsPage
